- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
Added examplify() which generates a String by example. The output string will have the same pattern as the input string.
> Added examplify() which generates a String by example.

- pom.xml
The PR extracts versions of dependencies into properties to simplify the process of dependency bumping as with this PR they are all in the same place
> Put dependency versions in properties

- src/test/java/net/datafaker/NumberTest.java
The problem with `net.datafaker.NumberTest#testNumberBetweenContain` is that it fails if size from  `int size = Math.abs(random.nextInt(100));` at line 427 is `0`. 
This PR makes this test working for that boundary scenario as well
An example of failure
```
Expected: is a value less than <574511116>
but: <574511116> was equal to <574511116>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at net.datafaker.NumberTest.testNumberBetweenContain(NumberTest.java:434)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Dele …
```
> Flaky testNumberBetweenContain could fail if size is 0

- src/main/java/net/datafaker/Options.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
There 2 issues:
1. Current code can not resolve the code with varargs e.g. `Options.option`
2. Options does not have `option` method with `String` varargs which is implied by `FakeValuesService`
This PR adds check if there is varargs in method args and supports it, also adds `Options.option` with String varargs to make it working like
``` 
#{options.option '12','345','89','54321'}
```
the PR is same as https://github.com/DiUS/java-faker/pull/703
> Add support of methods with varargs and #{options.option ...}

- .github/workflows/maven.yml
The PR add a matrix with `windows-latest` and `macos-latest` and also LTS jdks (8, 11, 17) to make sure it could be built on any of them
>  Enable build for other platforms and other jdks

- .github/workflows/maven.yml
https://github.com/actions/setup-java#supported-distributions:
> **NOTE:** Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from `adopt` to `temurin` to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
> [CI] Use `temurin` instead of deprecated `adopt`

- src/main/java/net/datafaker/Twitter.java
- src/test/java/net/datafaker/NumberTest.java
- src/test/java/net/datafaker/TwitterTest.java
Sometimes `net.datafaker.TwitterTest#testLongTwitterIdLength` fails (exception below) because it could happen that length of `id1 + id2` less than expectedLength.
To reproduce it usually it is enough to add `@Repeat(times = 100 )` for `net.datafaker.TwitterTest#testLongTwitterIdLength`
This PR fixes this behavior
The exception
```
testLongTwitterIdLength(net.datafaker.TwitterTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.IllegalArgumentException: bound must be positive
at java.base/java.util.Random.nextInt(Random.java:388)
at net.datafaker.service.RandomService.nextInt(RandomService.java:29)
at net.datafaker.Twitter.twitterId(Twitter.java:85)
at net.datafaker.TwitterTest.testLongTwitterIdLength(TwitterTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Na …
```
> Flaky testLongTwitterIdLength case

- src/main/java/net/datafaker/Crypto.java
- src/test/java/net/datafaker/CryptoTest.java
It looks like there are missing `md2` and `sha384`. The PR adds support for them
If there is no objections I'll merge it soon
> Add missing md2 and sha384

- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
There are already present several functions to generate a string by template e.g.
`net.datafaker.Faker#letterify` or `net.datafaker.Faker#numerify`.
The problem is that `letterify` could fill template only with ascii symbols and `numerify` only with digits and it is impossible to fill one `?` with several symbols.
The idea of this PR is providing of `xrify` (not sure about naming, probably there might be better options) which takes a template and a set of string options which could be used to fill it e.g.
E.g. if I want to fill `?` with some Russian or Chinese strings
```
faker.templatify("12??34", '?', "тест", "test", "测试测试")
```
> Add templatify function to fill templates

- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
Another PR to speed up `faker.expression` a bit. 
The idea is to use map to access fakevalues in `FakeValuesGrouping` which is O(1) instead of collection which in O(n)
Some measurements shows about 20-30% improvement
before
```
Benchmark                            Mode  Cnt    Score    Error   Units
JmhTest._bothifyExpression          thrpt    5  533.255 ± 22.638  ops/ms
JmhTest._letterifyExpression        thrpt    5  531.161 ± 12.172  ops/ms
JmhTest._optionsExpression          thrpt    5  370.678 ± 16.982  ops/ms
JmhTest._regexifyExpression         thrpt    5  238.741 ± 15.081  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  337.323 ±  1.139  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   67.555 ±  6.570  ops/ms
```
after
```
Benchmark                            Mode  Cnt …
```
> Use Map of collections instead of collection to speed up access by path

- src/main/java/net/datafaker/service/FakeValuesService.java
The PR replaces slow regexp with concat and split
some results of measurements (for some scenarios it gives up to 40%)
before
```
Benchmark                            Mode  Cnt    Score    Error   Units
JmhTest._bothifyExpression          thrpt    5  601.265 ± 11.568  ops/ms
JmhTest._letterifyExpression        thrpt    5  619.345 ± 10.733  ops/ms
JmhTest._optionsExpression          thrpt    5  445.589 ±  4.059  ops/ms
JmhTest._regexifyExpression         thrpt    5  255.194 ±  4.645  ops/ms
JmhTest.firstName                   thrpt    5  476.731 ±  4.385  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  393.700 ±  2.009  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5  102.284 ±  1.653  ops/ms
```
after
```
JmhTest._bothifyExpression          thrpt    5   935.122 ± 11.105 …
```
> Replace Regexp with split or concat if possible

- src/main/java/net/datafaker/Sip.java
- src/test/java/net/datafaker/AbstractFakerTest.java
- src/test/java/net/datafaker/NameTest.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
The PR makes use of array instead of `ArrayList` in `Sip` to avoid boxing and autosizing.
Also it makes use of mocked `Faker` only in case it is required
This gives improvement for benchmark 
```java
@Benchmark
public void initFaker(Blackhole blackhole) {
blackhole.consume(new Faker());
}
```
before
```
JmhTest.initFaker                   thrpt    5   26.509 ±  0.214  ops/ms
```
after
```
JmhTest.initFaker                   thrpt    5    44.192 ± 0.733  ops/ms
```
> Use array for ports in Sip, use spy only when needed in tests

- src/main/java/net/datafaker/Faker.java
The PR makes `Faker` lazy.
It adds a map of class to provider and creates provider only when it was called first time instead of initialization of each of them in constructor.
Also it orders providers in abc order.
This also speeds up initialization of faker
before
```
Benchmark           Mode  Cnt    Score   Error   Units
JmhTest.initFaker  thrpt    5  138.761 ± 2.593  ops/ms
```
after
```
Benchmark                            Mode  Cnt    Score    Error   Units
JmhTest.initFaker                   thrpt    5  251.992 ±  2.641  ops/ms
```
> Make Faker lazy

- src/test/java/net/datafaker/NameTest.java
The problem with this test:  it assumes that first and middle names are never equals however based on yaml data it is not true.
So the PR changes check instead of non-equality to less than 10% 
Sometimes it fails e.g. here https://github.com/datafaker-net/datafaker/runs/5182593884?check_suite_focus=true
```
Expected: not "Miss"
but: was "Miss"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at net.datafaker.NameTest.testNameWithMiddleDoesNotHaveRepeatedName(NameTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at …
```
> Fix flaky testNameWithMiddleDoesNotHaveRepeatedName

- src/main/java/net/datafaker/Number.java
Use `BigDecimal.valueOf` instead of constructor speeds up _bothifyExpression and numberbetween in about 10%
before
```
JmhTest._bothifyExpression          thrpt    5  1082.865 ±  2.784  ops/ms
```
after
```
JmhTest._bothifyExpression          thrpt    5  1177.438 ± 18.784  ops/ms
```
> Use BigDecimal.valueOf instead of constructor

- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
Another PR with replacement of regexp
This one also adds + up to  70% for some cases
before
```
JmhTest._bothifyExpression          thrpt    5  1000.702 ±  9.367  ops/ms
JmhTest._letterifyExpression        thrpt    5   983.098 ± 18.326  ops/ms
JmhTest._optionsExpression          thrpt    5   675.234 ±  7.525  ops/ms
JmhTest._regexifyExpression         thrpt    5   310.129 ±  6.492  ops/ms
JmhTest.firstName                   thrpt    5   715.902 ± 13.890  ops/ms
JmhTest.initFaker                   thrpt    5   256.209 ±  0.784  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5   595.780 ±  5.652  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   166.082 ±  1.000  ops/ms
```
after
```
Benchmark …
```
> Replace regexp parser with normal parser of directive and arguments

- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
Since loading of files for English locale consume lots of time for init of Faker and at the same time files are always same. The PR extracts this loading to static which could drastically speed up initFaker
before
```
JmhTest.initFaker                   thrpt    5   237.218 ± 10.073  ops/ms
```
after
```
Benchmark                            Mode  Cnt     Score     Error   Units
JmhTest.initFaker                   thrpt    5  4181.729 ± 192.370  ops/ms
```
> Move file loading for english locale to static

- src/main/java/net/datafaker/service/FakeValuesService.java
The same idea as for suppliers at the PR https://github.com/datafaker-net/datafaker/pull/42 but for `Generex` objects
it also speeds up `regexify` cases
before
```
JmhTest._regexifyExpression         thrpt    5   366.460 ±  3.624  ops/ms
```
after
```
Benchmark                            Mode  Cnt     Score     Error   Units
JmhTest._regexifyExpression         thrpt    5  1649.755 ± 195.986  ops/ms
```
> Cache Generex objects

- src/main/java/net/datafaker/Csv.java
- src/test/java/net/datafaker/CsvTest.java
The PR adds support for csv generation
number and names of columns could be specified
separator and quotes could be specified with `separator()` and `quote()`
number of lines could be specified via `limit()`
with or without header also could be specified with `header()`
e.g. 
```
System.out.println(new Csv.CsvBuilder()
.columns(Csv.Column.of("first_name", () -> faker.name().firstName()),
Csv.Column.of("last_name", () -> faker.name().lastName()),
Csv.Column.of("address", () -> faker.address().streetAddress()))
.header(true)
.separator(" ; ")
.limit(5).build().get());
```
will generate something like that
```
"first_name" ; "last_name" ; "address"
"Jonah" ; "Kovacek" ; "009 Wilkinson Summit"
"John" ; "Murphy" ; "379 McCullough Locks"
"Colby" ; "Bins" ; "93534 Stevie Gardens"
"Wade" ; …
```
> Add csv generation

- src/main/java/net/datafaker/FakeCollection.java
- src/test/java/net/datafaker/FakeCollectionTest.java
The PR adds support of fake collections
e.g. will generate a list of first and last names with size `[3, 5]`
```java
List<String> names = new FakeCollection.Builder<String>()
.suppliers(() -> faker.name().firstName(), () -> faker.name().lastName())
.minLen(3)
.maxLen(5).build().get();
```
List could contain different types e.g.
```java
List<Object> objects = new FakeCollection.Builder<>()
.suppliers(() -> faker.name().firstName(), () -> faker.random().nextInt(100))
.maxLen(5).build().get();
```
> Add fake collections

- src/main/java/net/datafaker/Internet.java
- src/test/java/net/datafaker/InternetTest.java
The PR adds generation of `InetAddress` objects both for `IPv4` and `IPv6`
> Generate InetAdresses for ipv4 and ipv6

- src/main/java/net/datafaker/Commerce.java
- src/main/java/net/datafaker/Company.java
- src/main/java/net/datafaker/Crypto.java
- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/File.java
- src/test/java/net/datafaker/AddressTest.java
- src/test/java/net/datafaker/CommerceTest.java
- src/test/java/net/datafaker/FinanceTest.java
The part about usage locales within `toUpperCase`, `toLowerCase` and `DecimalFormatSymbols`
> Use locale for toUpperCase, toLowerCase, decimal format symbols

- .github/workflows/maven.yml
Could be helpful to see where time is consuming
the result could be seen in build logs at https://github.com/datafaker-net/datafaker/runs/5303678498?check_suite_focus=true#step:4:7
> Add flags to maven to show timestamps during build

- src/main/java/net/datafaker/Lorem.java
- src/main/java/net/datafaker/service/RandomService.java
- src/test/java/net/datafaker/InternetPasswordTest.java
The PR speeds up a bit _Lorem#characters_ and it's dependencies e.g. _Internet#password_
before
```
Benchmark           Mode  Cnt     Score    Error   Units
JmhTest._password  thrpt    5  4710.876 ± 45.822  ops/ms
```
after
```
Benchmark           Mode  Cnt     Score    Error   Units
JmhTest._password  thrpt    5  5254.761 ± 21.613  ops/ms
```
benchmark
```java
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@State(Scope.Benchmark)
@Fork(value = 2, jvmArgs = {"-Xms2G", "-Xmx2G"})
public class JmhTest {
private static final Faker FAKER = new Faker();
public static void main(String[] args) throws RunnerException {
Options opt = new OptionsBuilder()
.include(JmhTest.class.getSimpleName())
.forks(1)
.build();
new Runner(opt).run();
}
@Benchmark …
```
> Speed up Lorem#characters and it's dependencies

- src/main/java/net/datafaker/Lorem.java
- src/main/java/net/datafaker/Number.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/RandomService.java
Suddenly this relatively simple change also speeds up some cases
before 
```
JmhTest._bothifyExpression          thrpt    5  4277.270 ± 41.760  ops/ms
JmhTest._csv                        thrpt    5    35.568 ±  0.919  ops/ms
JmhTest._letterifyExpression        thrpt    5  4629.480 ± 62.134  ops/ms
JmhTest._optionsExpression          thrpt    5  4846.367 ± 34.680  ops/ms
JmhTest._regexifyExpression         thrpt    5  2070.759 ± 23.280  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  2309.779 ± 26.963  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   565.426 ±  5.828  ops/ms
```
after
```
JmhTest._bothifyExpression          thrpt …
```
> Use ThreadLocalRandom wherever possible since it is available since 1.7

- src/main/java/net/datafaker/service/FakeValuesService.java
This change drastically speeds up almost all cases
```
JmhTest._bothifyExpression          thrpt    5  4538.392 ± 60.038  ops/ms
JmhTest._letterifyExpression        thrpt    5  4834.415 ± 89.559  ops/ms
JmhTest._optionsExpression          thrpt    5  4894.174 ± 59.062  ops/ms
JmhTest._regexifyExpression         thrpt    5  2099.060 ± 35.080  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  4688.254 ± 71.117  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   590.847 ±  7.354  ops/ms
```
after
```
Benchmark                            Mode  Cnt      Score     Error   Units
JmhTest._bothifyExpression          thrpt    5  19174.442 ± 295.380  ops/ms
JmhTest._letterifyExpression        thrpt    5  19171.794 ± …
```
> Cache mapping of raw expressions to suppliers

- src/main/java/net/datafaker/service/FakeValuesService.java
Small speedup.
For generation of different formats it could bring up to 30% e.g. for csv
before
```
Benchmark                            Mode  Cnt     Score     Error   Units
JmhTest._csv                        thrpt    5    30.206 ±   0.538  ops/ms
```
after
```
Benchmark                            Mode  Cnt     Score     Error   Units
JmhTest._csv                        thrpt    5    40.923 ±   0.455  ops/ms
```
> Cache expressions for keys

- README.md
- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/Nigeria.java
- src/main/resources/en/nigeria.yml
- src/test/java/net/datafaker/AustraliaTest.java
- src/test/java/net/datafaker/NigeriaTest.java
Added Nigeria to the list of providers
> David Ogar

- src/main/java/net/datafaker/DateAndTime.java
- src/test/java/net/datafaker/DateAndTimeTest.java
The PR adds generation of Duration for units: `day`, `hour`, `minute`, `second`, `millis`, `nanos`
e.g.
```
faker.date().duration(123, "day");
faker.date().duration(123, "days");
faker.date().duration(123, "hour");
faker.date().duration(123, "hours");
faker.date().duration(123, "minute");
faker.date().duration(123, "minutes");
```
and also possible to specify min boundary
```
faker.date().duration(3, 123, "day");
faker.date().duration(12, 123, "days");
faker.date().duration(32, 123, "hour");
faker.date().duration(43, 123, "hours");
faker.date().duration(34, 123, "minute");
faker.date().duration(121, 123, "minutes");
```
> Add generation of duration

- docs/documentation/custom-providers.md
- src/main/java/net/datafaker/Faker.java
- src/test/java/net/datafaker/CustomFakerTest.java
The PR makes possible to add paths to custom faker's data not only from `net.datafaker` package
> Add addPath at Faker's level

- src/main/java/net/datafaker/FakeCollection.java
- src/main/java/net/datafaker/fileformats/Csv.java
- src/main/java/net/datafaker/fileformats/Format.java
- src/test/java/net/datafaker/FakeCollectionTest.java
- src/test/java/net/datafaker/fileformats/CsvTest.java
The PR generalize `toCsv` for fake collections and simple column based.
Now for both it could be done with `Format.toCsv` e.g.
```java
String csv = Format.toCsv(
Csv.Column.of("values", () -> "1,2,3"),
Csv.Column.of("title", () -> "The \"fabulous\" artist"))
.header(true)
.separator(",")
.limit(1).build().get();
```
or
```java
String separator = "$$$";
int limit = 5;
String csv = Format.toCsv(
new FakeCollection.Builder<Data>().minLen(limit).maxLen(limit)
.suppliers(BloodPressure::new, Glucose::new, Temperature::new)
.build())
.headers(() -> "name", () -> "value", () -> "range", () -> "unit")
.columns(Data::name, Data::value, Data::range, Data::unit)
.separator(separator)
.build().get();
```
> Introduce Format and generalise logic for csv

- src/main/java/net/datafaker/fileformats/Format.java
- src/main/java/net/datafaker/fileformats/Json.java
- src/test/java/net/datafaker/FakeCollectionTest.java
- src/test/java/net/datafaker/fileformats/JsonTest.java
The PR adds toJson for fakeCollections, also adds builders to simplify usage (no more maps are required) e.g.
```java
System.out.println(
Format.toJson(new FakeCollection.Builder<Name>().faker(faker)
.suppliers(() -> faker.name())
.maxLen(10)
.minLen(10)
.build())
.set("title", Name::title)
.set("name", Name::name)
.set("lastname", Name::lastName)
.set("username", Name::username)
.build()
.generate()
);
```
will lead to
```
[{"title": "Investor Functionality Director", "name": "Thi Keebler", "lastname": "Jenkins", "username": "soila.raynor"},
{"title": "Regional Brand Assistant", "name": "Eva Runte", "lastname": "Predovic", "username": "wilford.johns"},
{"title": "Customer Directives Orchestrator", "name": "Noble Rosenbaum", "lastname": "Murphy", "username": "maxima.rempel"},
{"title": …
```
> Add toJson for fake collections

- src/main/java/net/datafaker/fileformats/Json.java
- src/test/java/net/datafaker/FakeCollectionTest.java
The PR adds possibility to builid complex json e.g.
```java
String json =
Format.toJson(new FakeCollection.Builder<Name>().faker(faker)
.suppliers(() -> faker.name())
.maxLen(2)
.minLen(2)
.build())
.set("address", Format.toJson(new FakeCollection.Builder<Address>().faker(faker)
.suppliers(() -> faker.address())
.maxLen(1)
.minLen(1)
.build())
.set("country", Address::country)
.set("city", Address::city)
.set("zipcode", Address::zipCode)
.set("streetAddress", Address::streetAddress)
.build())
.set("phones", name -> new FakeCollection.Builder<String>().suppliers(() -> faker.phoneNumber().phoneNumber()).maxLen(3).build().get())
.build()
.generate();
System.out.println(json);
```
gives
```json
[{"address": [{"country": "Haiti", "city": "South Lessieton", "zipcode": "71379", "streetAddress": …
```
> Allow nested json in builders

- src/main/java/net/datafaker/Vehicle.java
The old regex used would skip the 'R' character when generating vins. It was a pretty small problem and required only simple changes, so I didn't raise an issue or write any tests.
Let me know if I need to do anything else !!!!
> Update VIN_REGEX used for Vehicle class

- src/main/java/net/datafaker/Sip.java
The PR fixes floating `net.datafaker.SipTest#bodyBytes_isNotNull` which sometimes could fail as at https://github.com/datafaker-net/datafaker/runs/5863983082?check_suite_focus=true#step:4:387
```
java.lang.ArrayIndexOutOfBoundsException: Index 5001 out of bounds for length 5001
at net.datafaker.Sip.rtpPort(Sip.java:56)
at net.datafaker.Sip.bodyString(Sip.java:190)
at net.datafaker.Sip.bodyBytes(Sip.java:200)
at net.datafaker.SipTest.bodyBytes_isNotNull(SipTest.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
> Upper bound for rtp port should be exclusive

- src/main/java/net/datafaker/passportnumbers/AmPassportNumber.java
- src/main/java/net/datafaker/passportnumbers/ChPassportNumber.java
Fix typos JavaDoc in AmPassportNumber
Fix all variables starting with "ch" to "am" in AmPassportNumber
> Fix typos in PassportNumber classes

- src/main/java/net/datafaker/Options.java
- src/test/java/net/datafaker/OptionsTest.java
The PR adds `subset` to pick a  subset of unique elements from provided options limited by size e.g.
```java
faker.options().subset(2, new String[]{"abc", "def", "ghi", "abc"});
```
will return a set with 2 unique elements.
If a specified size is 0 it will return empty set.
If a specified size is larger than a number of unique elements in options then it will return a set with all unique options
> Add Options.subset

- docs/documentation/collections.md
- docs/documentation/file-formats.md
- src/main/java/net/datafaker/Faker.java
- src/test/java/net/datafaker/FakeCollectionTest.java
The PR adds synonym for `new FakeCollection.Builder<>()` 
now it is possible to create collection like 
```java
faker.collection()
.suppliers(
() -> faker.name().firstName(), 
() -> faker.random().nextInt(100))
.maxLen(5)
.build().get();
```
The old approach keeps working as well
> Add faker#collection as a synonym for new FakeCollection.Builder()

- src/main/java/net/datafaker/Address.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/AbstractFakerTest.java
- src/test/java/net/datafaker/AddressTest.java
- src/test/java/net/datafaker/CommerceTest.java
- src/test/java/net/datafaker/service/FakeValuesTest.java
The PR does 2 things
1. Allows to run single tests from _net.datafaker.AddressTest_ and _net.datafaker.CommerceTest_
2. Allows to configure exception message for _FakeValuesService#resolve_ to be able to be more precise wit the reason instead of just having something like 
```
resulted in null expression
at com.github.javafaker.service.FakeValuesService.resolve(FakeValuesService.java:308)
at com.github.javafaker.Address.countyByZipCode(Address.java:43)
```
e.g. like at https://github.com/DiUS/java-faker/issues/702
> Make exception message configurable in FakeValuesService#resolve

- src/main/java/net/datafaker/DateAndTime.java
- src/test/java/net/datafaker/DateAndTimeTest.java
The PR optimizes birthday by eliminating of useless objects creation
before
```
Benchmark           Mode  Cnt    Score   Error   Units
JmhTest._birthday  thrpt    5  258.748 ± 0.649  ops/ms
```
after
```
Benchmark           Mode  Cnt    Score   Error   Units
JmhTest._birthday  thrpt    5  409.440 ± 0.982  ops/ms
```
> Optimize birthday

- README.md
- src/test/java/net/datafaker/SoulKnightTest.java
The PR fixes missing symbols in regex for SoulKnightTest to fix ci failing like https://github.com/datafaker-net/datafaker/runs/6622190178?check_suite_focus=true
> Add missing symbols in regex for SoulKnightTest

- src/main/java/net/datafaker/service/FakeValuesService.java
The PR adds caching for fetching objects
It allows to speed up expressions where more than one method should be called 
Before
```
Benchmark                                       Mode  Cnt     Score    Error   Units
DatafakerBenchmark.address                     thrpt    5   109.668 ±  1.462  ops/ms
DatafakerBenchmark.oneMethodCallExpression     thrpt    5  1087.463 ± 24.951  ops/ms
DatafakerBenchmark.threeMethodsCallExpression  thrpt    5   281.641 ±  7.682  ops/ms
```
After
```
Benchmark                                       Mode  Cnt     Score    Error   Units
DatafakerBenchmark.address                     thrpt    5   119.390 ±  1.479  ops/ms
DatafakerBenchmark.oneMethodCallExpression     thrpt    5  1088.493 ± 19.085  ops/ms
DatafakerBenchmark.threeMethodsCallExpression  thrpt    5 …
```
> Add caching for fetching object by keys

- src/main/java/net/datafaker/Number.java
- src/test/java/net/datafaker/NumberTest.java
The PR makes use of primitive int and long wherever possible
It leads to speed up of `Number#numberBetween`
Before
```
Benchmark                              Mode  Cnt     Score    Error   Units
DatafakerSimpleMethods.numberBetween  thrpt   10  5342.357 ± 77.561  ops/ms
```
After
```
Benchmark                              Mode  Cnt       Score       Error   Units
DatafakerSimpleMethods.numberBetween  thrpt   10  168671.569 ± 18585.414  ops/ms
```
> Use primitive int, long to generate numbers if possible

- docs/documentation/performance.md
The PR is aiming to show comparison of performance between datafaker and javafaker,  jFairy, kotlin-Faker across different jdks.
There is a separate project https://github.com/snuyanzin/datafaker-benchmark which could be used for some measurements
> Add doc about perf comparison

- src/main/java/net/datafaker/idnumbers/EnIdNumber.java
- src/main/java/net/datafaker/passportnumbers/AmPassportNumber.java
- src/main/java/net/datafaker/passportnumbers/ChPassportNumber.java
- src/test/java/net/datafaker/PassportTest.java
For perf reasons it's better to use precompiled `Pattern` than compiling `String` each time
> Use Pattern instead of String for matching

- src/main/java/net/datafaker/Address.java
- src/test/java/net/datafaker/AddressTest.java
The PR fixing failing longitude/latitude test https://github.com/datafaker-net/datafaker/runs/6810315041?check_suite_focus=true#step:4:854
> Use decimal number format for longitude, latitude instead of computerized scientific notation

- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
The PR allows to do some actions in a different locale within same `Faker` object, e.g.
```java
faker.name().firstName() + " "
+ faker.doWith(() -> faker.name().lastName(), Locale.SIMPLIFIED_CHINESE) + " "
+ faker.doWith(() -> faker.name().nameWithMiddle(), new Locale("ru-RU"));
```
Could lead to `Demarcus 罗 Тамара Григорьевна Комиссарова`
Update: also could be used in colections/csv and etc. e.g.
```java
Function<Locale, Supplier<String>> firstNameSupplier = locale -> () -> faker.doWith(() -> faker.name().firstName(), locale);
String csv = Format.toCsv(
Csv.Column.of("CA First Name", firstNameSupplier.apply(Locale.CANADA)),
Csv.Column.of("CN First Name", firstNameSupplier.apply(Locale.SIMPLIFIED_CHINESE)),
Csv.Column.of("DE First Name", …
```
> Add support of doWith

- pom.xml
- src/test/java/net/datafaker/MbtiTest.java
Add autoformatter `spotless` (https://github.com/diffplug/spotless) embedded into build
Apply google format (version 7) format. Version 7 since it still supports java8.
**Currently it is set to check unused imports only**
Now in case of violations it could being automatically fixed (including removal of unused imports) with `mvn spotless:apply` (this will be also mentioned in error message).
Here the format fix is the result of `mvn spotless:apply`
> Set spotless checking unused imports

- src/main/java/net/datafaker/internal/helper/WordUtils.java
Add fast return for the case of already capitalized strings instead of creating new objects
> Add fast return if a string is already capitalized

- src/main/java/net/datafaker/Address.java
The PR makes delimiter for `latLon` and `lonLat` configurable. Defaults to `,`
> Make delimiter for latLon and lonLat configurable

- README.md
I noticed that in the README some providers' names have spaces and some don't, so I corrected them to more readable ones.
> Add space between providers' names

- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
The PR allows to pass `seed` within `doWith`
now it's possible to pass seed like
```java
faker.doWith(() -> faker.name().firstName(), 123);
```
or both seed and locale
```java
faker.doWith(() -> faker.name().firstName(), Locale.GERMAN, 123);
```
> Add possibility to pass seed to FakeValuesService

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/CodeTest.java
- src/test/java/net/datafaker/integration/FakerIntegrationTest.java
~~The strange thing about passports is that it generates something strange and then in a loop tries to check if the result of generation is ok or not.
For instance,  in `net.datafaker.passportnumbers.ChPassportNumber#getValidCh` it tries to generates something with regex `[A-Z][0-9A-Z][0-9]{7}` and then checks result against `E\\d\\d{7}` and `G\\d{8}`. It is much faster to generate based on expected data.~~
Update fix concurrent issue at https://github.com/datafaker-net/datafaker/runs/7640952734?check_suite_focus=true
> Make concurrent tests more stable

- src/main/java/net/datafaker/Internet.java
- src/main/java/net/datafaker/service/RandomService.java
- src/test/java/net/datafaker/InternetTest.java
First PR to this project, feel free to provide feedback on what to change.
Added:
* internet().uuidv3()
* nextRandomBytes()
* Two tests: one whether the format is correct and one to test whether constant random seeds do what they're supposed to (which is the entire reason for this PR)
Notes:
* Using 16 bytes for generating UUID since it covers the entire UUID
* maven site didn't work locally, I hope the provided javadocs are okay
* It's also unclear how versioning works, should I increase the minor version?
* Should I add something to the changelog?
> #285: Add internet().uuidv3()

- docs/documentation/file-formats.md
This PR adds a small CSV format example using a fake collection builder. To be honest, I just copy-pasted the example from the repository's README. But this should make it easier for people to understand how it works without having to go to the GitHub repository. Let me know what you think.
See #278.
> Add CSV format example using a fake collection builder

- src/test/java/net/datafaker/PhoneNumberValidityFinderTest.java
I want to propose lower error count in the test, all the locales (except for 2, they are not actually phone numbers locale, I will raise an issue later on this) are now under 50 error count threshold, so I think it would be better to lower error count in order to be able to detect some incorrect phone number formats, and improve them more.
> Change error count threshold value in PhoneNumberValidityFinderTest.testAllPhoneNumber

- pom.xml
Suddenly datafakers moves shaded classes under `com.github.javafaker...` The PR fixes that.
Also it stops generation of dependency-reduced pom since it is not used within the project
> Do not create dependency-reduced-pom, use datafaker's path for shaded classes

- .github/workflows/maven.yml
There is an issue with current ci job naming that it's impossible to get enough info from dropdown list without clicking on details...
See also picture
The Pr changes a bit naming to fix this behavior
> Improve naming of ci jobs

- src/main/java/net/datafaker/Vehicle.java
- src/main/resources/en/vehicle.yml
- src/test/java/net/datafaker/VehicleTest.java
Adds colors and fabrics for upholstery to the Vehicle provider. As well as a method for a combination of both.
I needed this for a use case I'm currently implementing.
> Add upholstery fabrics and colors to Vehicle provider

- src/test/java/net/datafaker/VehicleTest.java
Fixes flaky test introduced in #355.
The pattern expects a single word, while one of the possible values consists of 2 words. Used a different pattern for the test.
> Fix flaky test

- src/main/java/net/datafaker/Hashing.java
- src/test/java/net/datafaker/HashingTest.java
In some cases it's possible to have MD5 hash (and possibly other as well) with the first byte set to 0. In this case it gets removed, while converting to BigInteger and the hex string has 31 characters. To make sure that it works as expected, we need to guarantee proper padding.
> Make sure that padding is used in Hashing

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/AbstractFakerTest.java
- src/test/java/net/datafaker/FakerTest.java
- src/test/java/net/datafaker/InternetTest.java
- src/test/java/net/datafaker/idnumbers/PeselNumberTest.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
- src/test/java/net/datafaker/service/RandomServiceTest.java
The PR makes open mocks in autoclosable, removes usage of deprecated `Faker#instance` and fix some warnings about assertJ methods
> Put open mocks in try catch

- src/main/java/net/datafaker/base/IdNumber.java
The PR reduces creation of id related objects
> Move id number objects to final fields to decrease number of object creations

- src/main/java/net/datafaker/base/Internet.java
- src/main/resources/en/internet.yml
- src/test/java/net/datafaker/base/InternetTest.java
Support Bot User Agent like https://github.com/faker-ruby/faker/pull/2477 .
> Support Bot User Agent

- src/main/java/net/datafaker/base/Internet.java
- src/main/resources/en/internet.yml
- src/test/java/net/datafaker/base/InternetTest.java
Issue: #404 
Replaced Lorempixel image utility with Lorem Picsum. Removed Lorempixel from the code.
> Implemented LoremPicsum

- README.md
- src/main/java/net/datafaker/service/files/EnFile.java
- src/main/java/net/datafaker/sport/Cricket.java
- src/main/java/net/datafaker/sport/SportProviders.java
- src/main/resources/en/cricket.yml
- src/test/java/net/datafaker/sport/CricketTest.java
> Added Cricket Provider

- src/main/java/net/datafaker/service/FakeValuesService.java
Use `getParameterCount` rather than `getParameterTypes` since `getParameterTypes` each time clones an array
> Use getParameterCount rather than getParameterTypes where possible

- src/main/java/net/datafaker/service/FakeValuesService.java
Reorder method calls inside `FakeValuesService#resolveExpression` to make it more lazy
> Reorder method calls in FakeValuesService#resolveExpression

- src/main/java/net/datafaker/service/FakeValuesService.java
The PR extracts common logic into `retrieveMethodAccessor`
Also it applies some optimizations to `javaNameToYamlName`
> Extract retrieveMethodAccessor method, optimize javaNameToYamlName

- src/main/java/net/datafaker/service/FakeValuesService.java
For final classes `isAssignableFrom` could be replaced with `==` to avoid calling native methods
> Replace isAssignableFrom with == for final classes, refactor retrieveMethodAccessor

- src/main/java/net/datafaker/transformations/CompositeField.java
- src/main/java/net/datafaker/transformations/CsvTransformer.java
- src/main/java/net/datafaker/transformations/Field.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/main/java/net/datafaker/transformations/Schema.java
- src/main/java/net/datafaker/transformations/SimpleField.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/main/java/net/datafaker/transformations/Transformer.java
- src/test/java/net/datafaker/fileformats/CsvTest.java
- src/test/java/net/datafaker/fileformats/JsonTest.java
- src/test/java/net/datafaker/fileformats/SqlTest.java
The PR introduces schemas for transformations mentioned at https://github.com/datafaker-net/datafaker/issues/429
Also it introduce a new SQL transformer
an example of usage
```java
System.out.println(
new SqlTransformer.SqlTransformerBuilder()
.build()
.generate(
faker.collection(faker::name).len(5).generate(),
Schema.of(field("name", Name::fullName), field("username", Name::username))));
```
which results to
```sql
insert into "MyTable" ("name", "username") values ('Joel Adams', 'darren.wiza');
insert into "MyTable" ("name", "username") values ('Cameron Runolfsdottir', 'kayla.robel');
insert into "MyTable" ("name", "username") values ('Justin Ernser', 'michel.anderson');
insert into "MyTable" ("name", "username") values ('Mauro Pouros', 'jesus.schulist'); …
```
> Introduce transformation schemas

- README.md
- docs/documentation/custom-providers.md
The PR fixes some missed master branch names during migration to main
> Correct main branch name

- src/main/java/net/datafaker/formats/Csv.java
- src/main/java/net/datafaker/formats/Format.java
- src/main/java/net/datafaker/formats/Json.java
- src/main/java/net/datafaker/transformations/Casing.java
- src/main/java/net/datafaker/transformations/SqlDialect.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
The PR adds supports of several SQL dialects 
e.g. for postgres there is `"` as a sql quote identifier , for MSSQL it's `[]`, for some other dbs it's `
e.g. for postgresql
```sql
INSERT INTO "MyTable" ("key") VALUES ('value');
INSERT INTO "MyTable" ("number") VALUES (123);
INSERT INTO "MyTable" ("number") VALUES (123.0);
```
for MSSQL
```sql
INSERT INTO [MyTable] ([number]) VALUES (123.123);
INSERT INTO [MyTable] ([boolean]) VALUES (true);
```
to generate the following code could be used
```java
SqlTransformer<?> transformer = new SqlTransformer.SqlTransformerBuilder().dialect(SqlDialect.MSSQL).build();
transformer.generate(Schema.of(field("number", () -> 123.123)), 1);
```
possible output
```sql
INSERT INTO [MyTable] ([number]) VALUES (123.123);
```
same for postgres
```java …
```
> Add support of sql dialect while sql generation

- src/test/java/net/datafaker/idnumbers/ZhCNIdNumberTest.java
- src/test/java/net/datafaker/providers/base/BookTest.java
- src/test/java/net/datafaker/providers/base/CannabisTest.java
- src/test/java/net/datafaker/providers/base/ChiquitoTest.java
- src/test/java/net/datafaker/providers/base/ConstructionTest.java
- src/test/java/net/datafaker/providers/base/DungeonsAndDragonsTest.java
- src/test/java/net/datafaker/providers/base/InternetPasswordTest.java
- src/test/java/net/datafaker/providers/base/OverwatchTest.java
- src/test/java/net/datafaker/providers/base/TronTest.java
- src/test/java/net/datafaker/providers/foods/CoffeeTest.java
- src/test/java/net/datafaker/providers/movie/Babylon5Test.java
- src/test/java/net/datafaker/providers/movie/DarkSoulTest.java
- src/test/java/net/datafaker/providers/movie/DetectiveConanTest.java
- src/test/java/net/datafaker/providers/movie/DuneTest.java
- src/test/java/net/datafaker/providers/movie/FinalSpaceTest.java
- src/test/java/net/datafaker/providers/movie/HeyArnoldTest.java
- src/test/java/net/datafaker/providers/movie/HitchhikersGuideToTheGalaxyTest.java
- src/test/java/net/datafaker/providers/movie/HobbitTest.java
- src/test/java/net/datafaker/providers/movie/LebowskiTest.java
- src/test/java/net/datafaker/providers/movie/SeinfeldTest.java
- src/test/java/net/datafaker/providers/movie/SimpsonsTest.java
- src/test/java/net/datafaker/providers/movie/StarTrekTest.java
- src/test/java/net/datafaker/providers/sport/CricketTest.java
- src/test/java/net/datafaker/providers/sport/FootballTest.java
Consistently use static imports for AssertJ, as a once of code change, [through OpenRewrite](https://docs.openrewrite.org/reference/recipes/java/testing/assertj/assertj).
```
mvn org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run \
-Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.30.0 \
-DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
```
> Run AssertJ best practices OpenRewrite recipe

- src/main/java/net/datafaker/transformations/CsvTransformer.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/main/java/net/datafaker/transformations/Transformer.java
- src/test/java/net/datafaker/formats/CsvTest.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/formats/SqlTest.java
@snuyanzin  could you review generics in Transformer interface, please?
I've found a number of issues here:
1. On the code below, `Schema<?, ? extends OUT>` means that `OUT transform(IN input)` function from `Field` interface could generate the value only of some specific type. For example for `CsvTransformer` class, `OUT` is defined as `CharSequence`, so it means that we can generate CSV only from CharSequence, we couldn't generate CSV (fields) from other objects (integer, double, boolean e.g.). 
Take a look on the test case `testCsvWithDifferentObjects` and `testCsvWithDifferentObjectsFunction`.
```java
public interface Transformer<IN extends AbstractProvider<?>, OUT> {
OUT apply(Object input, Schema<?, ? extends OUT> schema);
...
```
2. Here, `IN` generic type should not extends …
> Rework Generics of Transformer interface

- .gitignore
- .idea/vcs.xml
Add navigation link to Github PR or Issue in IntellijIdea
P.S. Similar way it was done for Spark and Flink e.g. https://issues.apache.org/jira/browse/SPARK-35223
> Add issue navigator link for idea

- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
Now it's possible to specify sql table schema like
```java
SqlTransformer<String> transformer =
new SqlTransformer.SqlTransformerBuilder<String>()
.schemaName("MySchema").tableName("MyTable").dialect(SqlDialect.MSSQL).build();
transformer.generate(Schema.of(field("nullValue", () -> null)), 1)
```
possible output is
```sql
INSERT INTO [MySchema].[MyTable] ([nullValue]) VALUES (null);
```
> Add support for table schema in sql transformer

- src/main/java/net/datafaker/transformations/Casing.java
- src/main/java/net/datafaker/transformations/CsvTransformer.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/main/java/net/datafaker/transformations/SqlDialect.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/main/java/net/datafaker/transformations/Transformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
The PR adds support for batch insert, e.g.
```java
Schema<String, String> schema =
Schema.of(field("firstName", () -> faker.name().firstName()),
field("lastName", () -> faker.name().lastName()));
SqlTransformer<String> transformer =
new SqlTransformer.SqlTransformerBuilder<String>()
.batch(true).dialect(SqlDialect.POSTGRES).build();
final int limit = 5;
String output = transformer.generate(schema, limit);
System.out.println(output);
```
will result in something like
```sql
INSERT INTO "MyTable" ("firstName", "lastName")
VALUES ('Lyman', 'Kessler'),
('Loriann', 'Lowe'),
('Gaynell', 'Blick'),
('Kallie', 'Kohler'),
('Rosalee', 'Armstrong');
```
Also keyword case support e.g.
```java
Schema<String, String> schema = …
```
> Add batch support and keyword case support for sql

- src/main/java/net/datafaker/transformations/SqlDialect.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/main/java/net/datafaker/transformations/TriFunction.java
- src/test/java/net/datafaker/formats/SqlTest.java
As usual one dialect could break everything...
e.g. batch insert for postgres looks like
```sql
INSERT INTO "MyTable" ("firstName", "lastName")
VALUES ('Candi', 'Kling'),
('Piedad', 'Fisher'),
('Antony', 'Brown'),
('Rick', 'Lueilwitz'),
('Tillie', 'Murazik');
```
while batch insert for Oracle looks like
```sql
INSERT ALL
INTO "MyTable" ("firstName", "lastName") VALUES ('Lanny', 'Roob'),
INTO "MyTable" ("firstName", "lastName") VALUES ('Vera', 'Carroll'),
INTO "MyTable" ("firstName", "lastName") VALUES ('Rolf', 'Boyle'),
INTO "MyTable" ("firstName", "lastName") VALUES ('Tonja', 'Bednar'),
INTO "MyTable" ("firstName", "lastName") VALUES ('Wyatt', 'Predovic')
SELECT 1 FROM dual;
```
This PR adds this kind of support
> Add support for batch insert for Oracle

- src/main/java/net/datafaker/sequence/FakeCollection.java
- src/main/java/net/datafaker/sequence/FakeSequence.java
- src/main/java/net/datafaker/sequence/FakeStream.java
- src/test/java/net/datafaker/sequence/FakeCollectionTest.java
- src/test/java/net/datafaker/sequence/FakeStreamTest.java
To allow to iterate by fake sequence like this:
```java
FakeSequence<String> digits = faker
.stream(() -> faker.number().digit())
.len(10)
.build();
for (String digit : digits) 
System.out.println(digit);
```
> Make FakeSequence Iterable

- src/main/java/net/datafaker/transformations/CsvTransformer.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/main/java/net/datafaker/transformations/Transformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
For example, such code:
```java
BaseFaker faker = new BaseFaker(new Random(10L));
Schema<Object, ?> schema = Schema.of(
field("Text", () -> faker.name().firstName()),
field("Bool", () -> faker.bool().bool())
);
SqlTransformer<Object> transformer = new SqlTransformer.SqlTransformerBuilder<>().build();
String sql = transformer.generate(schema, 2);
```
Computes such a result:
`INSERT INTO "MyTable" ("Text", "Bool") VALUES ('Willis', false)INSERT INTO "MyTable" ("Text", "Bool") VALUES ('Carlena', true);`
But I'm expecting to get:
`INSERT INTO "MyTable" ("Text", "Bool") VALUES ('Willis', false);`
`INSERT INTO "MyTable" ("Text", "Bool") VALUES ('Carlena', true);`
Also, added some little improvement in API of Transformer interface
> [bug-fix] generate separated SQL statements

- src/main/java/net/datafaker/transformations/SqlDialect.java
- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
Some databases support `ARRAY` and  `MULTISET`
this PR adds support for it.
So if there is a field in `Schema` with value of array or list then it will be transformed into sql `ARRAY`
like
```java
Schema.of(field("bytes", () -> new byte[]{1, 0}));
```
With help of this `Schema` there could be generated sql like
```sql
INSERT INTO "MyTable" ("bytes") VALUES (ARRAY[1, 0]);
```
In a similar way for `MULTISET`, a filed should be a set like
```java
Schema.of(field("names_multiset", () -> Collections.singleton(faker.name().firstName())));
```
it could generate a sql like
```sql
INSERT INTO "MyTable" ("names_multiset") VALUES (MULTISET['Carlena']);
```
> Add support for array and multiset

- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
Yes these things could be nested
e.g. this Schema
```java
Schema.of(field("ints_ints", () -> new int[][]{new int[]{1}, null, new int[] {3, 4, 5}}))
```
allows to generate something like that
```sql
INSERT INTO "MyTable" ("ints_ints") VALUES (ARRAY[ARRAY[1], NULL, ARRAY[3, 4, 5]]);
```
and this one
```java
Schema.of(field("array_multiset", () -> Collections.singletonList(Collections.singleton("value"))))
```
could help with generation of mix
```sql
INSERT INTO "MyTable" ("array_multiset") VALUES (ARRAY[MULTISET['value']]);
```
> SQL arrays and multisets could be nested

- src/main/java/net/datafaker/transformations/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
Oopss, forgot that in SQL `MULTISET` could contain duplicates...
the PR fixes that
now everything that is array goes to sql `ARRAY`
everything that is java `Collection` goes to sql `MULTISET`
> Multiset could contain duplicates

- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
There could be a weird environment when a table or schema or field name contain a catalog separator...
In this case sql quoting should be used
> Use sql quote identifier if schema or table or field name contain catalog separator

- src/test/java/net/datafaker/formats/SqlTest.java
A bit more crazy stuff...
SQL `ROW` is already supported, now more tests for that
so just with usage of `compositeField` it's possible to have SQL nested structure like `ROW`
e.g.
```java
Schema.of(compositeField("row_row",
new Field[]{field("name1", () -> "1"), compositeField("row", new Field[]{field("name", () -> "2")})}))
```
could be used to generate something like that
```sql
INSERT INTO "MyTable" ("row_row") VALUES (ROW('1', ROW('2')));
```
> Add tests for sql row

- src/main/java/net/datafaker/transformations/CsvTransformer.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/main/java/net/datafaker/transformations/Transformer.java
- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
- src/test/java/net/datafaker/formats/CsvTest.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/formats/SqlTest.java
1. Changed `List<IN>` to `FakeSequence<IN>` in generate function of Transformer interface.
2. Fix bug in SQL Transformer:
Example:
```java
BaseFaker faker = new BaseFaker(new Random(10L));
Schema<Integer, ?> schema = Schema.of(
field("Number", integer -> integer),
field("Password", integer -> faker.internet().password(integer, integer))
);
SqlTransformer<Integer> transformer = new SqlTransformer.SqlTransformerBuilder<Integer>().build();
// inputs = List or FakeSequence of size 5
String sql = transformer.generate(inputs, schema);
```
Expected to get **5** (size of inputs) SQL statements, but actual result is **2** (length of schema fields).
> Generate from FakeSequence instead of List + bug fix in sql generator

- src/main/java/net/datafaker/service/RandomService.java
The same approach as in https://github.com/datafaker-net/datafaker/pull/508
the same assumption
number of different digits is less then size of byte range and it is ok (16 vs 256)
So this allows it to speed up for about 30-40%
digitByDigit1 - current approach for 1 digit
digitByDigit10 - current approach for 10 digits
digitByDigit100 - current approach for 100 digits
and etc.
```
Benchmark            Mode  Cnt       Score       Error   Units
byteArrayBased1     thrpt   10  119909.324 ±   972.720  ops/ms
byteArrayBased10    thrpt   10   28427.346 ±  5152.356  ops/ms
byteArrayBased100   thrpt   10    4350.995 ±   276.395  ops/ms
byteArrayBased1000  thrpt   10     391.391 ±    55.684  ops/ms
digitByDigit1       thrpt   10   76420.584 ± 11843.538  ops/ms
digitByDigit10      thrpt   10 …
```
> Speed up hex by using getRandomByteArray

- src/main/java/net/datafaker/providers/base/Number.java
The idea is to use generation of random byte array to generate digits.
There is an assumption allowing it to work
number of different digits is less then size of byte range and it is ok (10 vs 256)
So this allows it to speed up for about 30-40% 
digitByDigit1 - current approach for 1 digit
digitByDigit10 - current approach for 10 digits
digitByDigit100 - current approach for 100 digits
and etc.
```
Benchmark            Mode  Cnt      Score      Error   Units
byteArrayBased1     thrpt   10  49607.067 ± 6887.798  ops/ms
byteArrayBased10    thrpt   10  15848.161 ± 1568.289  ops/ms
byteArrayBased100   thrpt   10   2170.854 ±   64.167  ops/ms
byteArrayBased1000  thrpt   10    226.260 ±    0.349  ops/ms
digitByDigit1       thrpt   10  32256.580 ±  536.872  ops/ms
digitByDigit10      thrpt   10 …
```
> Speed up digit generation by using random byte array

- src/main/java/net/datafaker/service/FakeValuesService.java
results of measurements (almost twice for bothify)
before
```
Benchmark                            Mode  Cnt      Score       Error   Units
DatafakerTemplateStrings.bothify    thrpt   10  15713.850 ±  2229.838  ops/ms
DatafakerTemplateStrings.letterify  thrpt   10  42921.869 ±  4525.499  ops/ms
DatafakerTemplateStrings.numerify   thrpt   10  34054.217 ± 10869.288  ops/ms
```
after
```
Benchmark                            Mode  Cnt      Score      Error   Units
DatafakerTemplateStrings.bothify    thrpt   10  26830.873 ±  849.909  ops/ms
DatafakerTemplateStrings.letterify  thrpt   10  43706.715 ± 5250.235  ops/ms
DatafakerTemplateStrings.numerify   thrpt   10  39695.582 ± 9124.170  ops/ms
```
> Speed up bothify by making it via one run

- src/test/java/net/datafaker/providers/base/TimeTest.java
Coverage of `Time` provider is 100% now
> Add tests for uncovered method in Time provider

- src/main/java/net/datafaker/providers/base/Code.java
The PR speeds `Code#isbnGroup` and `Code#isbnGs1` by usage `Options` instead regexify
comparison
```
Benchmark                         Mode  Cnt      Score      Error   Units
DatafakerSimpleMethods.option    thrpt   10  50185.955 ± 5028.459  ops/ms
DatafakerSimpleMethods.regexify  thrpt   10   6889.025 ±  379.912  ops/ms
```
> 10x times speed up Code#isbnGroup and Code#isbnGs1 by usage of Options

- src/main/java/net/datafaker/formats/Yaml.java
- src/main/java/net/datafaker/transformations/YamlTransformer.java
- src/test/java/net/datafaker/formats/YamlTest.java
The PR introduces yaml transformer.
An example of usage
```
System.out.println(
new YamlTransformer<Name>().generate(
faker.collection(faker::name).len(1).build(),
Schema.of(field("name", Name::fullName), field("username", Name::username))));
```
Result:
```
name: Mabelle Prohaska
username: clara.lemke
```
> Support transformation schema for YAML

- src/main/java/net/datafaker/providers/base/Aws.java
- src/main/java/net/datafaker/providers/base/Azure.java
Usage of `hex` instead of `regexify` makes about 20x times faster
```
Benchmark                         Mode  Cnt      Score     Error   Units
DatafakerSimpleMethods.hex       thrpt   10  22772.434 ± 178.039  ops/ms
DatafakerSimpleMethods.regexify  thrpt   10   1034.842 ± 157.265  ops/ms
```
for tests
```java
@Benchmark
public void regexify(Blackhole blackhole) {
blackhole.consume(DATA_FAKER.regexify("[a-f0-9]{16}"));
}
@Benchmark
public void hex(Blackhole blackhole) {
blackhole.consume(DATA_FAKER.random().hex(16, false));
}
```
> 20x times speed up Aws and Azure by using hex

- src/main/java/net/datafaker/providers/base/Aws.java
- src/main/java/net/datafaker/providers/base/Text.java
- src/test/java/net/datafaker/formats/CsvTest.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/formats/SqlTest.java
By usage of assumption that in case of number of different symbols less than or equals 256 it's possible to use generated byte array and symbols should be unique it could be drastically speed up 
before 
```
Benchmark                        Mode  Cnt     Score     Error   Units
DatafakerSimpleMethods.text10   thrpt   10  1451.104 ± 125.972  ops/ms
DatafakerSimpleMethods.text100  thrpt   10   164.296 ±  20.433  ops/ms
```
after
```
Benchmark                        Mode  Cnt     Score     Error   Units
DatafakerSimpleMethods.text10   thrpt   10  4360.216 ± 529.892  ops/ms
DatafakerSimpleMethods.text100  thrpt   10   895.668 ±  98.985  ops/ms
```
benchmark
```java
...
private static final net.datafaker.Faker DATA_FAKER = new net.datafaker.Faker();
Text.TextRuleConfig config10 = …
```
> Use getRandomBytes and specific hashcode to speed up text generation

- src/main/java/net/datafaker/providers/base/Aws.java
Speed up `net.datafaker.providers.base.Aws#route53ZoneId` by moving textconfig to a class field
before
```
Benchmark                              Mode  Cnt     Score    Error   Units
DatafakerSimpleMethods.route53ZoneId  thrpt   10  1318.496 ± 11.038  ops/ms
```
after
```
Benchmark                              Mode  Cnt     Score     Error   Units
DatafakerSimpleMethods.route53ZoneId  thrpt   10  3636.202 ± 547.198  ops/ms
```
> 3x times speed up Aws#route53ZoneId by moving textConfig in Aws to class field

- docs/documentation/formats.md
- docs/documentation/schema.md
- mkdocs.yml
- src/main/java/net/datafaker/transformations/CsvTransformer.java
fixes #498 
cc @panilya  since you've asked about it
> Add documentation for schemas

- src/main/java/net/datafaker/providers/base/Aws.java
- src/main/java/net/datafaker/providers/base/Internet.java
- src/main/java/net/datafaker/providers/base/Text.java
- src/test/java/net/datafaker/providers/base/TextTest.java
Caching of text configs brings about 20% of speed
before
```
Benchmark                                         Mode  Cnt     Score    Error   Units
DatafakerPassword.password10                     thrpt   10  1293.016 ± 38.115  ops/ms
DatafakerPassword.password10WithUpper            thrpt   10  1059.780 ± 83.480  ops/ms
DatafakerPassword.password10WithUpperLower       thrpt   10   963.004 ± 79.944  ops/ms
DatafakerPassword.password10WithUpperLowerDigit  thrpt   10   992.366 ± 32.792  ops/ms
```
after
```
Benchmark                                         Mode  Cnt     Score     Error   Units
DatafakerPassword.password10                     thrpt   10  1577.841 ± 112.689  ops/ms
DatafakerPassword.password10WithUpper            thrpt   10  1262.548 ±  74.436  ops/ms …
```
> Speed up text generation, remove faker from text config builder

- src/main/java/net/datafaker/providers/base/Text.java
- src/test/java/net/datafaker/providers/base/TextTest.java
The result of measurement 
before
```
Benchmark           Mode  Cnt     Score     Error   Units
Text.password10   thrpt   10  3324.275 ± 207.978  ops/ms
Text.password100  thrpt   10   953.392 ±   7.367  ops/ms
```
after
```
Benchmark           Mode  Cnt     Score     Error   Units
Text.password10   thrpt   10  9167.557 ± 195.276  ops/ms
Text.password100  thrpt   10  1722.053 ±  87.599  ops/ms
```
> Speed up text generation by removal map

- src/main/java/net/datafaker/service/FakeValuesService.java
Also brings some speed improvements for cases of methods invocations via expressions e.g.
before
```
Benchmark                                      Mode  Cnt     Score    Error   Units
DatafakerExpressions.numberbetweenExpression  thrpt   10  2806.942 ± 52.094  ops/ms
```
after
```
Benchmark                                      Mode  Cnt     Score     Error   Units
DatafakerExpressions.numberbetweenExpression  thrpt   10  3333.331 ± 246.507  ops/ms
```
test itself
```java
@Benchmark
public void numberbetweenExpression(Blackhole blackhole) {
blackhole.consume(DATA_FAKER.expression("#{number.number_between '1','10'}"));
}
```
> Add caching of remove underscore result

- src/main/java/net/datafaker/service/FakeValuesService.java
Also a bit speed up which gives about 10%
before
```
Benchmark                                      Mode  Cnt     Score     Error   Units
DatafakerExpressions.numberbetweenExpression  thrpt   10  3333.331 ± 246.507  ops/ms
```
after
```
Benchmark                                      Mode  Cnt     Score    Error   Units
DatafakerExpressions.numberbetweenExpression  thrpt   10  3666.636 ± 26.251  ops/ms
```
> Use already found dot index

- README.md
- src/main/java/net/datafaker/providers/sport/Baseball.java
- src/main/java/net/datafaker/providers/sport/SportProviders.java
- src/main/java/net/datafaker/service/files/EnFile.java
- src/main/resources/en/baseball.yml
- src/test/java/net/datafaker/providers/sport/BaseballTest.java
Added Baseball provider under Sport package with issue #547
> Add Baseball provider

- src/main/java/net/datafaker/service/FakeValuesService.java
There is no need to call random to pick a random element from list in case there is less than 2 elements
> Do not call Random for singletone lists

- docs/documentation/custom-providers.md
IProviders has been renamed to BaseProviders in #376. This pull request updates the code samples in custom-providers.md.
> Documentation update: rename IProviders to BaseProviders

- src/main/java/net/datafaker/service/FakeValues.java
- src/test/java/net/datafaker/service/FakeValuesTest.java
> Make call to FakeValues#loadValues once

- src/main/java/net/datafaker/service/FakeValuesService.java
Based on measurements with array it is 3 times faster
before
```
JavaToYamlName.javaNameToYamlName  thrpt   10  16956.250 ± 210.104  ops/ms
```
after
```
JavaToYamlName.javaNameToYamlName  thrpt   10  48621.566 ± 270.788  ops/ms
```
> Speed up javaNameToYamlName by usage of array

- src/main/java/net/datafaker/service/FakeValues.java
Usage of array instead of `StringBuilder` speeds up more than 2 times
before 
```
Benchmark                Mode  Cnt      Score     Error   Units
ToJavaName.toJavaName2  thrpt   10  21737.634 ± 552.641  ops/ms
```
after
```
Benchmark                Mode  Cnt      Score     Error   Units
ToJavaName.toJavaName   thrpt   10  57957.671 ± 783.179  ops/ms
```
> Speed up FakeValues#toJavaNames

- src/test/java/net/datafaker/script/ProvidersDocsGenerator.java
> Fix generation of invalid links in ProvidersDocsGenerator

- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/main/java/net/datafaker/providers/base/Locality.java
Descrease number of exceptions in case of empty filename
Make it returning supported locales both for jars and source
Also there is support for custom locales added via custom providers
e.g.
```java
faker.locality().allSupportedLocales(Set.of("datafaker", "custom jar"));
```
in args need to pass jar names to look at
should fix #566
> Return supported locales

- src/main/java/net/datafaker/service/FakeValuesService.java
There is a useless throwing of exception in case there is no any method  found and then just log it...
Instead it should be just logged without throwing
> Log error instead of throwing and catching

- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesService.java
This is a small optimization which allows to speed up a bit nested expressions e.g.
```yaml
street_name:
- "#{Name.first_name} #{street_suffix}"
- "#{Name.last_name} #{street_suffix}"
```
before
```
Benchmark                              Mode  Cnt    Score   Error   Units
DatafakerSimpleMethods.streetAddress  thrpt   10  551.874 ± 7.358  ops/ms
```
after
```
DatafakerSimpleMethods.streetAddress  thrpt   10   682.915 ±  5.474  ops/ms
```
> Preload classes and methods while parsing yaml

- src/main/resources/nl.yml
Expanding `suffix` collection + adjusting `name` patterns: we shouldn't use default (en) since and is en in Dutch, thus I added
```
name:
- "#{Name.last_name} #{suffix}"
- "#{Name.last_name}-#{Name.last_name}"
- "#{Name.last_name}, #{Name.last_name} en #{Name.last_name}"
```
> Enhance NL local company name and suffix

- src/main/resources/da-DK.yml
- src/main/resources/dk.yml
Ticket: https://github.com/datafaker-net/datafaker/issues/642
> #642 - Language code for Denmark is 'da'

- pom.xml
Use https like it is done for maven itself https://issues.apache.org/jira/browse/MNG-6778
> Use https for schemaLocation

- src/main/java/net/datafaker/providers/base/Computer.java
- src/main/resources/en/computer.yml
- src/test/java/net/datafaker/providers/base/ComputerTest.java
Update the Computer faker with brands
> Computer brands feature request

- pom.xml
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
- JsonTransformer didn't have 4 indentation hence, the whitespace noise.
- Added JSONAssert to assist with json assertions. Did not update other test cases to use this.
> :technologist: JsonTransformer enhancement to support import scenarios

- src/test/java/net/datafaker/providers/base/GarmentSizeTest.java
Check the the value returned is one of the expected values, vs just not empty.
> Garment Size Test Tweak

- src/main/java/net/datafaker/providers/base/BaseProviders.java
- src/main/java/net/datafaker/providers/base/Zodiac.java
- src/main/java/net/datafaker/service/files/EnFile.java
- src/main/resources/en/zodiac.yml
- src/test/java/net/datafaker/providers/base/ZodiacTest.java
- BaseProvider.java > Hook Zodiac class.
- EnFile.java > Include Zodiac.yml.
- Zodiac.java > New Provider class.
- zodiac.yml > New data file for Zodiac signs.
- ZodiacTest.java > Unit Test for new provider.
> Add Zodiac Signs provider

- .gitattributes
Set .gitattributes to enforce the EOL as specified in editor config.
I'm developing on Windows, prior to tweaking this I was getting spotless check issues.
> Enforce EOL=LF

- docs/documentation/custom-providers.md
It's only possible to create a custom provider with BaseProviders instead of a Faker in it's constructor.
With Faker, it gets the following error: "reason: no instance(s) of type variable(s) exist so that BaseProviders conforms to Faker"
> Correct custom provider example

- .gitattributes
So that EOL don't accidentally get switched to CRLF (or mixed).
> Include XML files in .gitattributes as text

- src/main/resources/en/computer.yml
- Framework is gaining momentum (https://frame.work/)
- Gateway is a long time brand (how could we forget/miss that cow pattern logo 😉 https://gatewayusa.com/)
- Gigabyte not just motherboards and components, they do have laptops and desktops https://www.gigabyte.com/
Follow-up to: datafaker-net/datafaker#654 & datafaker-net/datafaker#652
> Add computer brands

- pom.xml
Related to: datafaker-net/datafaker#666
It seems the only outstanding items in the project are `-Xlint:deprecation` and `-Xlint:unchecked`.
Ultimately we'll be able to replace the individual options with `Xlint:all`. But while we're building toward that we may as well prevent these from creeping in :wink:
> implement currently passing Xlint checks

- docs/documentation/schemas.md
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/sequence/FakeCollectionTest.java
- src/test/java/net/datafaker/sequence/FakeStreamTest.java
Simplify invocation of json transformer builder in the same way like it is already done for sql transformer:
static builder method
> Add static builder method for json transformer

- README.md
- docs/documentation/schemas.md
`new CsvTransformer()` is private, now it should be used
`CsvTransformer.builder()`
> Use CsvTransformer#builder in doc

- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/sequence/FakeCollectionTest.java
PR adds object list support for JSON.
An example of usage
```
JsonTransformer.<Name>builder().build().generate(
Schema.of(
field("text", () -> "Mrs. Brian Braun"),
field("objectCollection", () -> List.of(
compositeField(null, new Field[]{
field("country", () -> "Denmark"),
field("city", () -> "Port Angel")
}
)
)
)
), 1);
```
Result:
```
{"text": "Mrs. Brian Braun", "objectCollection": [{"country": "Denmark", "city": "Port Angel"}]}
```
> Support list of objects for JSON

- src/test/java/net/datafaker/providers/base/AppTest.java
- src/test/java/net/datafaker/providers/base/HackerTest.java
- src/test/java/net/datafaker/providers/base/JobTest.java
- src/test/java/net/datafaker/providers/base/SlackEmojiTest.java
- src/test/java/net/datafaker/providers/base/SpaceTest.java
- src/test/java/net/datafaker/providers/base/TeamTest.java
I'd previously used the wrong syntax, luckily it didn't break things.
I'm sure there are a ton of places this should be changed further. I'll look at that for another PR.
> Fix non-capturing groups

- .github/workflows/maven.yml
- .github/workflows/qodana.yml
Qodana is a code quality platform similar to Snyk. This is an experiment to try it out. See for more info https://www.youtube.com/watch?v=WrhnUnzMUCg&t=203s or https://www.jetbrains.com/qodana/
> Added Qodana support (experiment)

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
> Do not cache methods of expressions with args

- src/main/java/net/datafaker/providers/entertainment/OscarMovie.java
- src/test/java/net/datafaker/providers/entertainment/OscarMovieTest.java
The issue is that `OscarMovie` stores field names in `year`, `choice`, `str` which are used to find out the next result. 
Providers should not do that, so just replace it with suppliers storing only the rules how to get such data but not the actual field names
fixes #741
> OscarMovie should store rules to access data but not the actual field names

- src/main/java/net/datafaker/annotations/Deterministic.java
- src/main/java/net/datafaker/providers/base/Address.java
- src/main/java/net/datafaker/providers/base/Drone.java
- src/main/java/net/datafaker/providers/base/Locality.java
- src/main/java/net/datafaker/providers/base/Mbti.java
- src/test/java/net/datafaker/FakerTest.java
- src/test/java/net/datafaker/providers/entertainment/OscarMovieTest.java
The PR is aiming to solve #741 for all the providers (not only `OscarMovie`)
E.g. it was detected that `Mbti` has same issue.
It retrieves all the declared public methods from provider with zero arg and invokes them several times.
The result is expected to be not the same at least for some of the invocations. 
As an exception there `Deterministic` annotation added to mark methods which are expected to return same value for any number of invocations.
> Add test of deterministic and non deterministic provider's methods

- src/test/java/net/datafaker/FakerTest.java
It looks like 10 is not enough for some cases e.g. https://github.com/datafaker-net/datafaker/actions/runs/4554807351/jobs/8033243612
Also there is no need to continue invocations in case set's size is >= 2
> Increase numberOfTestsPerMethod to 100 for testDeterministicAndNonDeterministicProvidersReturnValues

- src/test/java/net/datafaker/providers/base/BaseFakerTest.java
As discussed in: https://github.com/datafaker-net/datafaker/pull/762
Tested with entries such as:
`""` (empty)
`" "` (space)
`"	"` (tab)
`"\n"` (new line literal)
> BaseFakerTest - Assert that provider lists should not have blank entries

- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesContext.java
- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/service/FakeValuesGroupingTest.java
- src/test/java/net/datafaker/service/FakeValuesTest.java
The idea behind this PR is to init FakeValues only once per FakeValuesContext (determined by locale, path, url, filename),
right now it generates new FakeValues each time if it is not a default locale
It will allow to reduce GC/memory cost.
Also it was mentioned at #759 at these comments https://github.com/datafaker-net/datafaker/issues/759#issuecomment-1507346220 and https://github.com/datafaker-net/datafaker/issues/759#issuecomment-1507959256
The best benchmark illustrating improvement is time consumed for build (since junit5 tests in datafaker are running in concurrent mode)
e.g. here for this PR for ubuntu jdk17 it took 1 min, 0 sec[1] vs 1min 18 sec for the latest main[2]
same for jdk20 this PR [3] took 57 sec vs 1 min 14 sec for the latest main [4]
also locally `mvn clean verify` is …
> Introduce FakeValuesContext and FAKE_VALUES_MAP

- docs/documentation/schemas.md
- src/main/java/net/datafaker/annotations/FakeForSchema.java
- src/main/java/net/datafaker/annotations/FakeResolver.java
- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/test/java/net/datafaker/annotations/FakeAnnotationTest.java
- src/test/java/net/datafaker/annotations/dto/Person.java
This is a backport of https://github.com/datafaker-net/datafaker/pull/754
to 1.x which would be nice to have there for some projects
> [Backport to 1.x] Add annotation support for data classes based on JavaObjectTransformer

- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesContext.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/FakerContext.java
- src/main/java/net/datafaker/service/RegExpContext.java
The problem with `Objects.hash` is that it generates an array each time it is called.
Suppliers could be cached to avoid parsing of expressions each time
it gives speed up for a wide range of methods up to 50 %
expressions
```
before
Benchmark                        Mode  Cnt     Score     Error   Units
DatafakerExpressions.bothify    thrpt   10  5089.609 ± 112.084  ops/ms
DatafakerExpressions.letterify  thrpt   10  5706.392 ± 326.134  ops/ms
DatafakerExpressions.numerify   thrpt   10  6027.549 ±  87.064  ops/ms
DatafakerExpressions.regexify   thrpt   10  2826.806 ±  31.933  ops/ms
VS
after
Benchmark                        Mode  Cnt      Score     Error   Units
DatafakerExpressions.bothify    thrpt   10  10936.056 ±  39.143  ops/ms
DatafakerExpressions.letterify  thrpt   10  13036.411 ± …
```
> Introduce cache of suppliers and remove usage of Objects.hash to speed up

- src/main/java/net/datafaker/providers/entertainment/EntertainmentFaker.java
- src/main/java/net/datafaker/providers/food/FoodFaker.java
- src/main/java/net/datafaker/providers/sport/SportFaker.java
- src/main/java/net/datafaker/providers/videogame/VideoGameFaker.java
> Add call for super constructors

- pom.xml
It seems these 2 were missed
to double check the whole list of libs that are used during runtime and should and shaded this command could be used
```
mvn dependency:tree | grep compile
```
output
```
[INFO] +- org.yaml:snakeyaml:jar:2.0:compile
[INFO] +- com.github.mifmif:generex:jar:1.0.2:compile
[INFO] |  \- dk.brics.automaton:automaton:jar:1.11-8:compile
```
> Add shading for generex and automaton

- src/main/java/net/datafaker/annotations/FakeResolver.java
Creating a Schema object from the `FakeForSchema` annotation can be time-consuming, as it involves reflection, when generating more than one object with a default schema using `BaseFaker.populate(MyClass.class)`, the cache could increase significantly speed. The difference in speed is about 35%.
This pr solves this problem:
```
Before
Benchmark                                                 Mode  Cnt    Score    Error  Units
Datafaker_JavaObjectPopulateBenchmark.javaObjectPopulate  avgt   10  845.517 ± 56.535  ms/op
VS
After
Benchmark                                                 Mode  Cnt    Score    Error  Units
Datafaker_JavaObjectPopulateBenchmark.javaObjectPopulate  avgt   10  552.060 ± 25.132  ms/op
```
> Introduce cache of default schemas to FakeResolver

- pom.xml
Backport of #797 to 1.x
git cherry-pick
> [Backport-1.x]  Add shading for generex and automaton

- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
Backport of #811
git cherry-pick
> [Backport-1.x] Use consumer<Object> rather than consumer<Schema> (#811)

- src/main/java/net/datafaker/providers/base/Finance.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
```
XXXXYYYYC
where XXXX is Federal Reserve Routing Symbol, YYYY is ABA Institution Identifier, and C is the check digit.
...
The first two digits of the nine digit RTN must be in the ranges 00 through 12, 21 through 32, 61 through 72, or 80.
- 00 is used by the [United States Government](https://en.wikipedia.org/wiki/Federal_government_of_the_United_States)
- 01 through 12 are the "normal" routing numbers, and correspond to the 12 [Federal Reserve Banks](https://en.wikipedia.org/wiki/Federal_Reserve_Bank). For example, 0260-0959-3 is the routing number for Bank of America incoming wires in New York, with the initial "02" indicating the [Federal Reserve Bank of New York](https://en.wikipedia.org/wiki/Federal_Reserve_Bank_of_New_York).
- 21 through 32 were assigned only to [thrift …
```
> Generating US routing number (ABA RTN) in Finance provider.

- src/main/java/net/datafaker/providers/base/Finance.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
1. remove useless `System.out.println`
2. `regexify` and `String.format` are slow, so it's better avoid them if possible
> Eliminate System.out.println, speed up Finance#usRoutingNumber

- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/sequence/FakeCollectionTest.java
This a backport of https://github.com/datafaker-net/datafaker/pull/693 to 1.x
just a cherry pick + adapt to jdk8
> [Backport-1.x] Support list of objects for JSON

- src/main/java/net/datafaker/providers/base/Finance.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
> [Backport-1.x] Eliminate System.out.println, speed up Finance#usRoutingNumber (#825)

- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/test/java/net/datafaker/annotations/FakeAnnotationTest.java
- src/test/java/net/datafaker/annotations/dto/ComplexPersonJavaRecord.java
- src/test/java/net/datafaker/annotations/dto/PersonJavaRecord.java
- src/test/java/net/datafaker/transformations/JavaObjectTransformerTest.java
At the moment, Datafaker doesn't support Java Records. This PR addresses this problem
> Add Java Record support in JavaObjectTransformer

- src/main/java/net/datafaker/providers/base/Number.java
The test to check 
```java
@Test
void test() {
for (int i = 0; i < 100_000_000; i++) {
faker.number().numberBetween(-1000_000_000, 2000_000_000);
}
}
```
before the change it takes about 20x times longer to complete ...
the main idea is in case of overloading the limit use fallback to `long` instead of fallback to `BigDecimal`
> Speed up Number#numberBetween for int values

- src/main/java/net/datafaker/providers/base/Internet.java
- src/test/java/net/datafaker/providers/base/InternetTest.java
- Internet.java > Re-implement url. Have it leverage the new webdomain method (which contains the original url impl). The new url implementation creates a fully formed URL with random elements.
- InternetTest.java > Updated to test the new url and webdomain methods.
Fixes datafaker-net/datafaker#840
> Internet provider: re-implement url, add webdomain method

- src/test/java/net/datafaker/formats/XmlTest.java
- src/test/java/net/datafaker/integration/FakerIntegrationTest.java
- src/test/java/net/datafaker/integration/UkLocalDirectivesTest.java
- src/test/java/net/datafaker/providers/base/LoremTest.java
- src/test/java/net/datafaker/providers/base/OptionsTest.java
- src/test/java/net/datafaker/sequence/FakeCollectionTest.java
The result of migrating code from Java 8 to Java 17 syntax improvements.
> Chore: Remove duplicate 'import java util.List'

- src/main/java/net/datafaker/transformations/CsvTransformer.java
Every call to append leads to call of `ensureCapacity`. To minimize number of such calls we could use bulk append whenever possible
It wallows to speed up csv generation a bit 
before
```
Benchmark                  Mode  Cnt    Score   Error   Units
DatafakerCsvjson.csvJson  thrpt   10  183.571 ± 0.253  ops/ms
```
after
```
Benchmark                  Mode  Cnt    Score   Error   Units
DatafakerCsvjson.csvJson  thrpt   10  195.783 ± 1.837  ops/ms
```
> Use bulk append instead of symbol by symbol

- src/main/java/net/datafaker/transformations/CsvTransformer.java
This will bring some speed improvements
before 
```
Benchmark                  Mode  Cnt    Score   Error   Units
DatafakerCsvjson.csvJson  thrpt   10  195.783 ± 1.837  ops/ms
```
after
```
Benchmark                  Mode  Cnt    Score   Error   Units
DatafakerCsvjson.csvJson  thrpt   10  203.992 ± 2.447  ops/ms
```
> Use StringBuilder instead of StringJoiner

- src/main/java/net/datafaker/providers/base/Number.java
Use integer `pow` instead of `Math.pow`
This brings some speed since no need to deal with fractions
before 
```
Benchmark                              Mode  Cnt      Score     Error   Units
DatafakerSimpleMethods.numberBetween  thrpt   10  32624.208 ± 873.033  ops/ms
```
after
```
Benchmark                              Mode  Cnt      Score      Error   Units
DatafakerSimpleMethods.numberBetween  thrpt   10  94411.143 ± 6192.659  ops/ms
```
> Speed up Number#randomNumber

- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
In some cases it's possible to replace `StringBuilder` with `StringJoiner`
The problem of `StringBuilder#append` is that each time it checks for arrays size even if it makes adding of just one symbol... it consumes lots of time
before
```
Benchmark                  Mode  Cnt    Score   Error   Units
DatafakerCsvSql.sql       thrpt   10  203.876 ± 2.975  ops/ms
```
after
```
Benchmark                  Mode  Cnt    Score   Error   Units
DatafakerCsvSql.sql       thrpt   10  232.296 ± 3.526  ops/ms
```
> Speed up sql transformer

- src/main/java/net/datafaker/idnumbers/EnZAIdNumber.java
- src/main/java/net/datafaker/providers/entertainment/StarWars.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/providers/base/BaseFakerTest.java
The main issue is that during validation it generates new `SimpleDateFormat` object and throws exception too often...
The PR minimizes number of generated exception by usage of existing validations
> Speed up EnZa number validation

- src/main/java/net/datafaker/idnumbers/pt/br/DocumentFormatterUtil.java
- src/main/java/net/datafaker/idnumbers/pt/br/IdNumberGeneratorPtBrUtil.java
- src/test/java/net/datafaker/providers/base/CNPJTest.java
- src/test/java/net/datafaker/providers/base/PhoneNumberTest.java
The idea is pretty straightforward: minimize amount of `substring` and regexps
> Speed up cnpj

- src/main/java/net/datafaker/providers/base/Locality.java
I noticed that `Files.isDirectory` depends on the system and for me it takes a lot since it involves io operations...
The idea is to apply string operations (`endswith` and others first and only after io )
also extract creation of visitor from loop's iteration since it is always same
> Extract SimpleFileVisitor, replace isDirectory with isRegularFile and put this condition to the end

- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
In `net.datafaker.service.FakeValuesServiceTest` in tests every time it creates `SimpleDateFormat` instance... It is more effectively to use `DateTimeFormatter` which could be created once and reused
> Use DateTimeFormatter instead of SimpleDateFormat

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/script/ProviderGenerator.java
It's better to refer to classes and use their names/packages rather than hardcode them and try to not forget while refactoring
> Use refs to classes rather than hardcoded names

- src/main/java/net/datafaker/providers/base/Domain.java
The PR simplifies `Domain#validDomain` by specifying `.` as delimiter in `String.join` rather than just empty string.
Also make concatenation no more than 2 times
> Simplify Domain#validDomain

- src/main/java/net/datafaker/transformations/JsonTransformer.java
The idea is to invoke `StringBuilder` for larger peaces than just one symbol if possible to minimize amount of checks while `StringBuilder#append"
> Speed up json generation by minimizing of Stringbuilder append invocations

- src/main/java/net/datafaker/idnumbers/EnZAIdNumber.java
- src/test/java/net/datafaker/idnumbers/EnZAIdNumberTest.java
There is no need to transform int to string and then to parse it again...
Also amount of substrings could be decreased
> Speed up EnZAIdNumber#validSsn

- .github/workflows/dependency-review.yml
- .github/workflows/maven.yml
Revert https://github.com/datafaker-net/datafaker/pull/964 because it isn't working. I suspect they incorrectly/temporarily had a v4 tag.
> chore(deps): Downgrade codecov/codecov-action action to v3.1.4

- src/main/java/net/datafaker/idnumbers/KoKrIdNumber.java
Replace `StringBuilder` with array of chars allows to save cost because of no need to check for array limits each time like for `StringBuilder#append`
> Speed up KoKrIdNumber#generateDay

- src/main/java/net/datafaker/idnumbers/ZhCnIdNumber.java
This allows to speed up the method in about 30-40%
> Don't use StringBuilder in getValidSsn since length could be predicted

- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/test/java/net/datafaker/annotations/FakeAnnotationTest.java
This allows to have different elements in collection of populated objects and should fix #979
> Collection of populated elements should not be always same

- src/main/java/net/datafaker/providers/base/DrivingLicense.java
- src/test/java/net/datafaker/providers/base/DrivingLicenseTest.java
since there is no regexp expresion in driverlicense resource file=> there is no need for `regexify` call
> Simplify tests for driving license, remove useless regexify call

- pom.xml
Currently if anyone will try to build it with jdk 8
it will print a huge exception which requires time understand what is the issue...
with this approach it will just print 
```
[ERROR] Rule 0: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
[ERROR] Detected JDK version 1.8.0-372 (JAVA_HOME=<...>/jdk8/jre) is not in the allowed range [17,).
```
> Add enforcer plugin to get more human friendly error message for wrong jdk

- src/main/java/net/datafaker/providers/base/Finance.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
There is no easy way to control target country randomization when creating IBANs, because both `countryCodeToBasicBankAccountNumberPattern` and `createCountryCodeToBasicBankAccountNumberPatternMap()` are private.
This PR adds a `Finance.ibanSupportedCountries()` to allow finer control of scope.
Fixes  #1001
> Access the list of countries supported for IBAN

- pom.xml
The multi-release classes for the relocated snakeyaml dependency need to be relocated manually due to a bug in the Maven Shade plugin. The plugin only relocates the content but not the package structure itself. See https://issues.apache.org/jira/browse/MSHADE-406. This fixes #1007.
> Manually relocate snakeyaml multi-release classes.

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/RegExpContext.java
`current` is a unique object each time and not used by `RegExpContext`
at the same time it participates in `equals` which could be a reson of maps growing...
This should be removed
Probably is a reason of and should fix #1019
> Current shoud not be a part of context

- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Update mvn wrapper via `./mvnw wrapper:wrapper` command
also it adds check for checksum of downloaded maven distribution
there is a similar check for wrapper distribution, however it does not work well for Windows, that's why currently it is commented till https://issues.apache.org/jira/browse/MWRAPPER-103 is solved
> Add distributionSha256Sum for maven

- src/main/java/net/datafaker/providers/base/Code.java
- src/main/java/net/datafaker/providers/base/Internet.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
- src/test/java/net/datafaker/script/ProviderGenerator.java
If there is no need to replace by regexp then there is `String#replace` which is much faster than `replaceAll`, thus it's better to use it instead
> Use String#replace whenever possible

- src/main/java/net/datafaker/providers/base/Number.java
- src/main/java/net/datafaker/service/FakeValuesService.java
Replace some operations with bitwise operations since they in general a bit faster
> Use bitwise operations

- src/main/java/net/datafaker/providers/base/Aws.java
- src/test/java/net/datafaker/providers/base/AwsTest.java
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html
Fixes datafaker-net/datafaker#1076
> AWS vpc/subnet/securitygroup IDs now 17char

- src/main/java/net/datafaker/annotations/FakeResolver.java
- src/main/java/net/datafaker/providers/base/Locality.java
- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesService.java
Suddenly I realized that `indexOf(<String>)` is faster than `indexOf(<char>)` since the first one has jvm intrinsic...
So the PR makes use `indexOf(<String>)` 
it gives some speed e.g. could be checked with this test
```java
private static final Name name = new Faker().name();
@Test
void test() {
for (int i = 0; i < 500_000_000; i++) {
name.lastName();
}
}
```
for my machine before change it took 16-18 sec
after 9-10 sec (almost 2 times)
> Use indexof string

- pom.xml
- src/main/java/module-info.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
> Use RgxGen to cope with StackOverFlow

- pom.xml
- src/moditect/module-info.java
> Cannot use datafaker in a project that use module (module-info.java)

- docs/documentation/custom-providers.md
The `static` only makes sense when the class is defined as an inner class, but that is not mentioned, and was confusing me as well.
> Update doc to fit the latest source code version

- .github/workflows/maven.yml
- pom.xml
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/sequence/FakeCollectionTest.java
- src/test/java/net/datafaker/sequence/FakeStreamTest.java
This PR changes the `JsonTransformer` by generating the output as valid JSON data (except by the without comma approach). The output will always be valid when one or more data is generated.
Added extra `prettyPrint()` method to enable a more readable output.
- Added the `prettyPrint()` method into `JsonTransformer` class along with the `json` library
- This is set by default and will output the JSON value in a pretty print format
- When disabled, one line String is generated
- When using the `withCommaBetweenObjects`, the `prettyPrint()` is "disabled" (set to `false`) due to a parse error
- parse error when there's no comma for multiple items
- Refactored `JsonTest`, `FakeStreamTest`, and `FakeCollectionTest` for methods using the `JsonTransformer` class
> Changes in the Json Transform

- src/main/resources/en-NZ.yml
> Fix address for en-NZ locale

- src/test/java/net/datafaker/FakerTest.java
> Adding a regexify test case for metacharacters inside a character set

- src/main/java/net/datafaker/providers/base/Locality.java
This should fix #1170 
to reproduce use datafaker-gen, especially this PR this https://github.com/datafaker-net/datafaker-gen/pull/10
to check that it is fixed use same PR and run it with (assuming this fixed is built and installed in local maven repo)
```
./mvnw clean install -Ddatafaker.version=2.2.2-SNAPSHOT
```
> Parent filename could be null for resources in jar

- .github/workflows/maven.yml
the idea is to get main repo from datafaker-gen and build it and then run tests against latest datafaker version to be able to detect issue appearing only in downstream projects like e.g. #1170 or #1168 
currently this check is done only in case of jdk21 and ubuntu (in fact i do not see a real reason to test it with the whole matrix)
> Add tests against downstream project (datafaker-gen)

- src/main/java/net/datafaker/transformations/CsvTransformer.java
- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/main/java/net/datafaker/transformations/Transformer.java
- src/main/java/net/datafaker/transformations/XmlTransformer.java
- src/main/java/net/datafaker/transformations/YamlTransformer.java
- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
This adds a feature of streams generation in transformers
with it will be possible to make transformations with huge numbers like 
```java
BaseFaker faker = new BaseFaker(new Random(10L));
Schema<Object, ?> schema = Schema.of(
field("Text", () -> faker.name().firstName()),
field("Bool", () -> faker.bool().bool())
);
JsonTransformer<Object> transformer = JsonTransformer.builder().build();
Stream<CharSequence> json = transformer.generateStream(schema, 1000_000_000);
json.forEach(System.out::println);
```
> Initial support for streams in transformers

- src/test/java/net/datafaker/Issue759Test.java
... instead of just throwing an empty runtime exception.
Before this change, test might fail with an unclear message:
```java
java.lang.RuntimeException
at net.datafaker.Issue759.issue759Test(Issue759.java:93)
```
or the output of multiple failing tests might be mixed:
```java
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0
0 0 0
0 0 0
0 0 0
0
0 0 0 0 0
java.lang.RuntimeException
at net.datafaker.Issue759.issue759Test(Issue759.java:93)
```
Now the error message is clear:
```java
java.lang.AssertionError: Not all of s[0, 0, 0, 0, 0] are not equal to 20000
at net.datafaker.Issue759Test.issue759Test(Issue759Test.java:85)
```
To reproduce the issue, just put breakpoint, say, to any field of `WorkerThread`, run `Issue759` test in debug mode and resume the execution after …
> show actual values in error message

- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/test/java/net/datafaker/providers/base/CustomFakerTest.java
PR Modify the enrichment provider classes map in BaseFaker to store a complete list of generated FakerContext.
: #1190
This allows you to store multiple locals for one class in the net.datafaker.providers.base.BaseFaker#CLASSES map.
Before this, every call to the net.datafaker.providers.base.BaseFaker#getProvider(java.lang.Class<AP>, java.util.function.Function<PR,AP>, PR) method would overwrite the map for one class name, making the cache ineffective.
> Modify the enrichment provider classes map in BaseFaker 

- src/main/java/net/datafaker/idnumbers/EnZAIdNumber.java
- src/main/java/net/datafaker/idnumbers/SvSEIdNumber.java
- src/main/java/net/datafaker/internal/helper/FakerIDN.java
- src/main/java/net/datafaker/providers/base/Relationship.java
- src/test/java/net/datafaker/providers/base/PhoneNumberValidityFinderTest.java
- src/test/java/net/datafaker/providers/base/RelationshipTest.java
...instead of catching too generic exceptions (which is considered a bad practice because some unexpected problems might be ignored).
> catch only specific exceptions

- src/main/java/net/datafaker/providers/base/TimeAndDate.java
it happened when
1. random TimeUnit was chosen NANOSECOND, but
2. random "atMost" (in milliseconds) was chosen lesser than 1000000 (it's less than 1 millisecond), so upperBoundMillis was equal to 1 or 0.
Sample stack trace:
```
java.lang.IllegalArgumentException: bound must be positive: -1
at net.datafaker.service.RandomService.nextLong(RandomService.java:51)
at net.datafaker.providers.base.TimeAndDate.future(TimeAndDate.java:99)
at net.datafaker.providers.base.TimeAndDate.future(TimeAndDate.java:47)
at net.datafaker.providers.base.TimeAndDate.future(TimeAndDate.java:35)
at net.datafaker.providers.base.TimeAndDateTest.testFutureDate(TimeAndDateTest.java:28)
```
> Fix another flaky test `TimeAndDateTest.testFutureDate`

- src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
- src/main/java/net/datafaker/providers/base/TimeAndDate.java
- src/test/java/net/datafaker/providers/base/TimeAndDateTest.java
From the previous few PRs and conversations.
> Minor tweaks and cleanup

- src/test/java/net/datafaker/providers/base/AviationTest.java
Following the failure here: https://github.com/datafaker-net/datafaker/actions/runs/9324424830/job/25669623466#step:4:1
Which apparently only had a 1 in 4037 chance of happening on any given test run, lucky us :grinning:
I threw together this temporary test (I'm sure there are more elegant ways to do this, it was just a quick thing):
```java
@Test
void checkLengths() {
List<String> entries = getBaseList("aviation.airport");
System.out.println(entries.size());
Map<Integer, Integer> lenMap = new HashMap<>();
lenMap.put(1, 0);
lenMap.put(2, 0);
lenMap.put(3, 0);
lenMap.put(4, 0);
lenMap.put(5, 0);
lenMap.put(6, 0);
for (String entry : entries) {
Integer count = lenMap.get(entry.length());
count++;
lenMap.put(entry.length(), count);
if (entry.length() != 4) {
System.out.println(entry);
}
} …
```
> fix: Aviation Test

- src/main/java/net/datafaker/providers/base/Internet.java
- src/main/java/net/datafaker/providers/base/Text.java
`Internet#password` is very limited with its functionality and we should encourage users to use `Text` instead which covers much more cases
> Mark Internet#pass deprecated

- src/test/java/net/datafaker/providers/base/PhoneNumberTest.java
- src/test/java/net/datafaker/providers/base/PhoneNumberValidityFinderTest.java
the leading "0" makes the generated phone number an invalid in very rare cases in Argentina. For example, "011 1579-5896" was generated from AR pattern, but occurred to be invalid.
And it seems that "0" is still needed in Italy.
> fix flaky test: remove leasing "0" from generated phone number

- CONTRIBUTING.md
Follow-up to: datafaker-net/datafaker#1249
> Add dependency info to CONTRIBUTING

- src/main/java/net/datafaker/transformations/sql/SqlDialect.java
- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
###
Add Spark SQL support.
See "INSERT INTO" spec https://spark.apache.org/docs/3.2.1/sql-ref-syntax-dml-insert-into.html
There are some issues with existing design in order to support all Spark types. 
Spark SQL [has 3 complex data types](https://spark.apache.org/docs/latest/sql-ref-datatypes.html):
- Array
- Map
- Struct
Insertions look like this
```sql
-- Inserting an array
INSERT INTO MyTable (array_column) VALUES (ARRAY(1, 2, 3));
-- Inserting a map
INSERT INTO MyTable (map_column) VALUES (MAP('key1', 'value1', 'key2', 'value2'));
-- Inserting a struct
INSERT INTO MyTable (struct_column) VALUES (NAMED_STRUCT('field1', 'value1', 'field2', 'value2'));
```
So notable design changes are
- array start and end markers are now configurable with default "[", "]". Spark requires "(" and ")". …
> Add Spark SQL dialect

- src/main/java/net/datafaker/providers/base/BaseFaker.java
No need to keep in cache void methods or methods coming from Object/AbstractProvider
one of the findings while looking at #1263
> [hotfix] Skip void or methods coming from Object or AbstractProvider

- src/main/java/net/datafaker/transformations/Transformer.java
- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
Implementation supports both normal and batched generation.
> Implement generate stream for SQL transformer

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
If an expression has arguments it shouldn't be treated as "simple".
Tweak FaverValueService logic and add test to FakerValueServiceTest.
Fixes datafaker-net/datafaker#1274
> fix: expressions resolution

- docs/documentation/schemas.md
Mention how complex types map from Faker schema to Spark types.
> Document Spark SQL

- src/main/java/net/datafaker/providers/base/TimeAndDate.java
`TimeAndDate#past` methods use `minimum` input parameter of `long` type, but `TimeAndDate#future` methods - of `int` type. This change unifies API: `minimum` input parameter is always of `long` type
> Unify `TimeAndDate` provider API

- src/main/java/net/datafaker/service/FakeValues.java
This is a partial fix for the issue https://github.com/datafaker-net/datafaker/issues/1285.
Result before changes:
```
Time to process 1000000 values: 40.341209708s
```
Result after changes:
```
Time to process 1000000 values: 19.826039958s
```
Result with no locale:
```
Time to process 1000000 values: 2.310795584s
```
Results are based on the code here: https://github.com/vitaly-ivanov/datafaker-memory-leak/blob/main/app/src/main/kotlin/org/example/Performance.kt
Nulls were interpreted as no attempt to load
If values were missing for the specified locale, the `loadValues` method returned null instead of an empty map, resulting in subsequent attempts to load values into the cache.
> Improve performance when generating with a specific locale

- src/main/java/net/datafaker/service/FakeValuesService.java
This fixes #1285 
no need to recalculate same values for different locales
before 
```
Benchmark                                        Mode  Cnt     Score    Error   Units
LocalePerformanceBenchmark.en_fullname          thrpt   10  3160.491 ± 71.525  ops/ms
LocalePerformanceBenchmark.en_gb_fullname       thrpt   10    62.385 ±  6.717  ops/ms
LocalePerformanceBenchmark.en_gb_streetAddress  thrpt   10    46.018 ± 25.115  ops/ms
LocalePerformanceBenchmark.en_streetAddress     thrpt   10  2268.299 ± 37.201  ops/ms
```
after
```
Benchmark                                        Mode  Cnt     Score    Error   Units
LocalePerformanceBenchmark.en_fullname          thrpt   10  3168.236 ± 65.091  ops/ms
LocalePerformanceBenchmark.en_gb_fullname       thrpt   10  1829.919 ± 34.379  ops/ms …
```
> Use cache for fetchObject

- src/main/java/net/datafaker/providers/base/Internet.java
I've removed the deprecation annotations here, it's really not clear to me why these methods were deprecated, and what their replacement was. 
Eg, someone used to be able to do `faker.internet().password()`. How would someone do this now?
Like this?
```
faker.text().text(Text.TextSymbolsBuilder.builder()
.len(5)
.with(EN_LOWERCASE, 1)
.with(EN_UPPERCASE, 1)
.with(DIGITS, 1);
```
That seems overly complex for a password. If I'm missing something, please let me know, because I'm not sure what happened here.
> Undeprecated password generation methods.

- src/main/java/net/datafaker/transformations/sql/SqlDialect.java
- src/test/java/net/datafaker/formats/SqlTest.java
I was mistaken on the first PR https://github.com/datafaker-net/datafaker/pull/1261 
**Spark SQL supports multi-row inserts**
https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-dml-insert-into.html
Validated on Databricks that the following statement is accepted.
```sql
INSERT INTO `MY_TABLE` (`field1`, `field2`)
VALUES ('value1', 'value2'),
('value1', 'value2'),
('value1', 'value2'),
...
```
> Add multi-row/batch insert for Spark SQL

- src/main/java/net/datafaker/idnumbers/AlbanianIdNumber.java
- src/main/java/net/datafaker/idnumbers/AmericanIdNumber.java
- src/main/java/net/datafaker/idnumbers/BulgarianIdNumber.java
- src/main/java/net/datafaker/idnumbers/ChineseIdNumber.java
- src/main/java/net/datafaker/idnumbers/EstonianIdNumber.java
- src/main/java/net/datafaker/idnumbers/GeorgianIdNumber.java
- src/main/java/net/datafaker/idnumbers/IdNumberGenerator.java
- src/main/java/net/datafaker/idnumbers/MacedonianIdNumber.java
- src/main/java/net/datafaker/idnumbers/MexicanIdNumber.java
- src/main/java/net/datafaker/idnumbers/MoldovanIdNumber.java
- src/main/java/net/datafaker/idnumbers/PolishIdNumber.java
- src/main/java/net/datafaker/idnumbers/PortugueseIdNumber.java
- src/main/java/net/datafaker/idnumbers/SingaporeIdNumber.java
- src/main/java/net/datafaker/idnumbers/SouthAfricanIdNumber.java
- src/main/java/net/datafaker/idnumbers/SouthKoreanIdNumber.java
- src/main/java/net/datafaker/idnumbers/SwedenIdNumber.java
- src/main/java/net/datafaker/idnumbers/Utils.java
- src/main/java/net/datafaker/providers/base/AbstractProvider.java
- src/main/java/net/datafaker/providers/base/IdNumber.java
- src/main/java/net/datafaker/providers/base/PersonIdNumber.java
- src/main/java/net/datafaker/service/RandomService.java
- src/test/java/net/datafaker/idnumbers/AlbanianIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/EstonianIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/SingaporeIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/SouthAfricanIdNumberTest.java
- src/test/java/net/datafaker/service/RandomServiceTest.java
this commit adds method `IdNumber.valid(IdNumberRequest)` which returns a valid combination of ID number, birthday and gender.
```java
PersonIdNumber person = faker.idNumber().valid(new IdNumberRequest(18, 96, ANY));
PersonIdNumber person = faker.idNumber().valid(new IdNumberRequest(25, 45, FEMALE));
```
In many countries, ID Number contains or depends on birthday and/or gender.
We need to generate a valid person containing a valid combination of ID number, birthday and gender matching each other. 
Until now, it was possible to generate them separately, but they didn't always match each other:
```java
String idNumber = faker.idNumber().valid();  // contains birthday of 80 old man
LocalDate birthday = faker.timeAndDate().birthday();  // birthday of 16 old woman
```
> generate ID Number together with birthday and gender

- src/main/java/net/datafaker/internal/helper/FakerIDN.java
- src/main/java/net/datafaker/providers/base/AbstractProvider.java
- src/main/java/net/datafaker/providers/base/Address.java
- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/main/java/net/datafaker/providers/base/Image.java
- src/main/java/net/datafaker/providers/base/Internet.java
- src/main/java/net/datafaker/providers/base/Twitter.java
- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/RandomService.java
- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/test/java/net/datafaker/Issue759Test.java
- src/test/java/net/datafaker/LogFormatter.java
- src/test/java/net/datafaker/TestSetupExtension.java
- src/test/java/net/datafaker/ThreadLocalLogHandler.java
- src/test/java/net/datafaker/idnumbers/SouthKoreanIdNumberTest.java
- src/test/java/net/datafaker/integration/FakerIntegrationTest.java
- src/test/java/net/datafaker/integration/FakerRepeatabilityIntegrationTest.java
- src/test/java/net/datafaker/providers/base/AddressTest.java
- src/test/java/net/datafaker/providers/base/BaseFakerTest.java
- src/test/java/net/datafaker/providers/base/InternetTest.java
- src/test/java/net/datafaker/providers/base/NumberTest.java
- src/test/java/net/datafaker/providers/base/RandomFakerTest.java
- src/test/java/net/datafaker/providers/foods/HebrewFoodTest.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
- src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- src/test/resources/junit-platform.properties
- src/test/resources/logging.properties
This PR doesn't fix https://github.com/datafaker-net/datafaker/issues/1306, but makes much easier debugging such problems.
> improve error handling and logging

- src/main/java/net/datafaker/providers/videogame/Dota2.java
- src/main/resources/en/dota2.yml
- src/test/java/net/datafaker/providers/videogame/Dota2Test.java
- Added tier() and neutralItem() methods in Dota2.class
- Updated the data in dota2.yml
- Updated the test for dota2HeroQuote()
> Add tier() and neutralItem() methods in Dota2 VideoGameProvider and update data

- src/main/java/net/datafaker/providers/base/Locality.java
it may be needed in Spring Boot applications where datafaker*.jar is re-packaged into "spring*.jar" etc.
> #1343 search locales in all JAR files, not only in "datafaker*.jar"

- src/main/java/net/datafaker/providers/base/Locality.java
- src/test/java/net/datafaker/providers/base/LocalityTest.java
Now we don't scan classpath at all, but just return a hardcoded list of locales. Instead, we now have a unit-test that verifies that this list is up-to-date.
Related to:
- datafaker-net/datafaker#1343 
- datafaker-net/datafaker#1349
> #1343 simplify code for returning all available locales

- src/main/java/net/datafaker/idnumbers/ChineseIdNumber.java
- src/test/java/net/datafaker/idnumbers/ChineseIdNumberTest.java
> fix: the last digit of ChineseIdNumber

- src/main/java/net/datafaker/providers/base/ObjectMethods.java
- src/test/java/net/datafaker/providers/base/ObjectMethodsTest.java
> #1368 fix "Duplicate key error" when a custom faker has multiple methods with the same return type.

- CONTRIBUTING.md
Per: https://github.com/datafaker-net/datafaker/pull/1383#pullrequestreview-2371884160
> CONTRIBUTING address review comments

- src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
- src/main/java/net/datafaker/service/FakeValuesService.java
Instead of two-three separate calls like `containsKey`, `get` and `put`, now we use a single `computeIfAbsent`.
P.S. I would like to also deny method `CopyOnWriteMap.put()`, but it's still used in one place (that was harder to refactor).
> #1306 fix non-thread-safe usages of CopyOnWriteMap

- src/main/java/net/datafaker/idnumbers/SingaporeIdNumber.java
- src/main/java/net/datafaker/providers/base/DateAndTime.java
- src/main/java/net/datafaker/providers/base/TimeAndDate.java
- src/main/java/net/datafaker/service/RandomService.java
- src/test/java/net/datafaker/providers/base/TimeAndDateTest.java
- src/test/java/net/datafaker/service/RandomNumbersTest.java
- src/test/java/net/datafaker/service/RandomServiceTest.java
e.g.
* `randomService.nextInt(Integer.MIN_VALUE, Integer.MAX_VALUE)`
* `randomService.nextLong(Long.MIN_VALUE, Long.MAX_VALUE)`
> #1386 fix nextInt and nextLong with extreme boundaries

- src/main/java/net/datafaker/transformations/sql/SqlTransformer.java
- src/test/java/net/datafaker/formats/SqlTest.java
- src/test/resources/test.yml
Some thesaurus`s word will be truncate when I use datafaker to generate SQL, like Address,Book... That reason is when SqlTransformer calling the handledObjectToString method will be one by one add char to new Object ,but if miss quote char will be stop.
> fix generate sql will be truncate when quote char in word

- src/test/java/net/datafaker/providers/base/UniversityTest.java
Extended the expected regex to include a few characters with accents.
Addresses https://github.com/datafaker-net/datafaker/pull/1404#issuecomment-2436479028
~~Add recently introduced test artifact `test.txt` to `.gitignore`~~
FYI if anyone needs to run single UnitTest classes or methods locally you can use:
` ./mvnw test -Dtest=UniversityTest`
` ./mvnw test -Dtest=UniversityTest#testName`
syntax.
> fix: University tests

- src/main/java/net/datafaker/providers/base/Barcode.java
- src/main/java/net/datafaker/providers/base/DateAndTime.java
- src/main/java/net/datafaker/providers/base/Number.java
- src/main/java/net/datafaker/service/RandomService.java
- src/main/java/net/datafaker/service/Range.java
- src/test/java/net/datafaker/providers/base/NumberTest.java
- src/test/java/net/datafaker/providers/base/TimeAndDateTest.java
- src/test/java/net/datafaker/providers/base/UniqueTest.java
- src/test/java/net/datafaker/service/RandomNumbersTest.java
- src/test/java/net/datafaker/service/RandomServiceTest.java
- src/test/java/net/datafaker/service/RangeTest.java
Does the API look good? 
I mean, these names are quite long (but explicit):
```java
randomService.nextInt(Range.inclusive(2, 4));  // 2, 3, 4
randomService.nextInt(Range.inclusiveExclusive(2, 5)); // 2, 3, 4
randomService.nextLong(Range.exclusiveInclusive(2L, 5L)); // 3L, 4L, 5L
randomService.nextLong(Range.exclusive(2L, 5L)); // 3L, 4L
```
> Feature: new methods `nextInt(Range)` and `nextLong(Range)`

- src/test/java/net/datafaker/providers/base/UniversityTest.java
some university names contain "." character (e.g. "St. Andrews")
> fix flaky UniversityTest

- src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
- src/test/java/net/datafaker/FakerTest.java
- src/test/java/net/datafaker/Issue759Test.java
The default method `Map.getOrDefault` is not thread-safe: the condition `if (v == null && containsKey(key))` leaves `v = null` if the `key` was added by another thread exactly at the same moment. Then both conditions are true: `v==null` and `containsKey(key)`.
Now `CopyOnWriteMap.getOrDefault` does NOT check `containsKey(key)`. 
P.S. As a side-effect, `CopyOnWriteMap` doesn't allow putting `null` values to the map. But we don't need it anyway.
> #1412 fix concurrency issue in `CopyOnWriteMap`

- src/main/java/net/datafaker/idnumbers/SwedenIdNumber.java
- src/test/java/net/datafaker/idnumbers/SwedishIdNumberTest.java
swedish ssn cannot have format like XXXXXX-000X, the end number part has to be between 001 and 999
explanation: https://www4.skatteverket.se/rattsligvagledning/edition/2024.5/330242.html#update_20240802105842
Information obtained with help of @Jakub-Pazio and @Johannestegner
> swedish ssn cannot have format like XXXXXX-000X

- src/main/resources/en/dota2.yml
Recently a [new hero](https://www.dota2.com/kez?l=english) came out, I added him and his lines to our dota2.yml dataset
> Update Dota2Provider dota2.yml

- src/main/resources/pt-BR.yml
- src/test/java/net/datafaker/providers/base/PassportTest.java
Sources: [passports regex](https://community.zscaler.com/s/question/0D54u00009jZpJGCA0/international-passport-numbers-regex), [examples](https://regulaforensics.com/blog/brazilian-id-processing/)
> Brazil passport number

- src/main/java/net/datafaker/providers/entertainment/Movie.java
- src/main/resources/en/movie.yml
- src/test/java/net/datafaker/providers/entertainment/MovieTest.java
This PR adds the below method to the existing movie provider:
- `new Faker().movie().name();`
Functionality has been validated and tested locally.
> feature: add movie name to movie provider

- .github/workflows/pom_update.yml
- .github/workflows/release.yml
Follow-up to discussion in: https://github.com/datafaker-net/datafaker/issues/1412
> Automate rolling of SNAPSHOT version in pom

- src/main/java/net/datafaker/idnumbers/SwedenIdNumber.java
- src/test/java/net/datafaker/idnumbers/SwedishIdNumberTest.java
If a person is older than 100 years, their SSN should have a "+" as the separator.
I found that when I was using datafaker and it sometimes creates SSNs that look like "000229+XXXX," which is an invalid SSN because February 29 did not exist in the year 1900.
more info: https://swedish.identityinfo.net/personalidentitynumber
> swedish ssn symbol depends on birthday date of person

- src/main/java/net/datafaker/idnumbers/SwedenIdNumber.java
- src/test/java/net/datafaker/helpers/IdNumberPatterns.java
- src/test/java/net/datafaker/idnumbers/PolishIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/SwedishIdNumberTest.java
I see that `@ParametrizedTest` may be over-used. It causes "IFs" and logic in tests trying to handle all given values.
Sometimes it's better to just write plain old test without any IFs.
> simplify few tests

- docs/documentation/password.md
The Java example was missing the execution of the method `build()` at the end of using the `TextSymbolsBuilder`.
> Documentation: Add missing build() part to example

- src/main/resources/en-GB.yml
The most common UK specific domains ([ref](https://www.nominate.com/uk.shtml))
> UK top level internet domains

- src/main/java/net/datafaker/idnumbers/EstonianIdNumber.java
- src/main/java/net/datafaker/idnumbers/LatvianIdNumber.java
- src/main/resources/META-INF/services/net.datafaker.idnumbers.IdNumberGenerator
- src/test/java/net/datafaker/idnumbers/LatvianIdNumberTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
* We support two formats: old (before 01.07.2017) and new (since 01.07.2017)
* For generating invalid ID numbers, we use only the old format (for simplicity)
> Added support for generating Latvian id number

- docs/in-the-media/links.md
Realized the link to TCB 71 in https://github.com/datafaker-net/datafaker/commit/565a477935b48b25eac922d2a81251859f168c08 was incorrect
> Fix dead link

- .github/workflows/build.yml
so far only for PRs
still tend to think that for main it should be run to be sure it is still working
based on the doc https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-paths
> Do not run GH ci if code or configuration was not changed

- .github/workflows/build.yml
Inspired by [this post on LinkedIn](https://www.linkedin.com/posts/laurentbroudoux_arm-activity-7295081454189891586-t6yy?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAAC299sBAspEXK7yi4HueOvVFeTyVEHeFts,) I tried moving to ARM as well (See [ARM support for Github runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)) to see if this speeds things up. It seems it doesn't?
> Added ARM support to the build to see if that has performance benefits.

- src/test/java/net/datafaker/providers/base/BaseFakerTest.java
At some point of time there was introduced a work around for the case when parameterized test input is empty.
Since junit 5.12.x there is a special annotation flag for that, so just replacing old workaround with this flag usage.
Edit: Original intro was here: https://github.com/datafaker-net/datafaker/pull/677
> Use `allowZeroInvocations` junit feature instead of a WA

- docs/documentation/date-format.md
- src/main/java/net/datafaker/providers/base/DateAndTime.java
The `net.datafaker.providers.base.DateAndTime` has been marked for deprecation, an additional hint what should be used instead makes it easier to adapt the changes. Also updated the docs to `net.datafaker.providers.base.TimeAndDate`.
> Update docs for date faking

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/GenerationUtils.java
- src/test/java/net/datafaker/FakerTest.java
- src/test/java/net/datafaker/annotations/FakeAnnotationTest.java
Since `nextInt` is one of the top consumers while executing `numerify` the idea is to reduce amount of calls to `nextInt`. 
For instance if we need to execute `numerify` for `####` then 4 digit number should be generated.
Current approach is generation a digit for every `#`. At the same time if `#` are together we can first count them and generate one number and then pick digits for every `#`. Then only one call to `nextInt` will be required. 
For sure if amount of sharps is large then several calls will be required (because of limited amount of numbers for int)
I also tried `nextLong` however it works significantly slower than `nextInt`.
some measurements for 6 `#` like
```java
@Benchmark
public void numerify(Blackhole blackhole) { …
```
> Descrease amount of calls to nextInt for numerify

- .github/workflows/pom_update.yml
- .github/workflows/release-from-tag.yml
- Have the pom update workflow trigger when the release has completed. (Instead of being called, since a called workflow can't have greater permissions than the caller.)
- Also update the versions in README.md.
Fixes datafaker-net/datafaker#1488
Tested in this junk repo: https://github.com/kingthorin/dftest (which will be removed after this PR is merged).
> Finish Release Workflow

- pom.xml
- src/main/java/net/datafaker/providers/base/Locality.java
- src/main/java/net/datafaker/service/RandomService.java
- src/test/java/net/datafaker/providers/base/LocalityTest.java
- src/test/java/net/datafaker/service/RandomServiceTest.java
Add support for using custom `RandomGenerators` like `SplittableRandom` for improved speed and less overhead
> Support custom Random Generators

- src/main/java/net/datafaker/providers/base/File.java
- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/Range.java
- src/test/java/net/datafaker/providers/base/CommerceTest.java
- src/test/java/net/datafaker/providers/base/ComputerTest.java
- src/test/java/net/datafaker/providers/base/CountryTest.java
- src/test/java/net/datafaker/providers/base/NationTest.java
- src/test/java/net/datafaker/providers/base/RandomFakerTest.java
- src/test/java/net/datafaker/providers/base/ScienceTest.java
- src/test/java/net/datafaker/providers/base/SipTest.java
- src/test/java/net/datafaker/providers/foods/HebrewFoodTest.java
- src/test/java/net/datafaker/script/ProviderGenerator.java
- src/test/java/net/datafaker/service/FakeValuesGroupingTest.java
- src/test/java/net/datafaker/service/FakeValuesTest.java
fix IDEA warnings, apply its automatic suggestions.
> Refactoring

- src/test/java/net/datafaker/internal/helper/LazyEvaluatedTest.java
- src/test/java/net/datafaker/service/FakeValuesTest.java
The loading synchronization was later implemented in `LazyEvaluated`, and this commit adds a similar test `LazyEvaluatedTest`.
> remove old commented out test in FakeValuesTest

- src/main/java/net/datafaker/providers/base/Internet.java
- src/test/java/net/datafaker/providers/base/InternetTest.java
Trying to revert the formatting, I messed up my fork. So I thought it best to close the previous PR and start all over again.  Here is a new PR. Sorry for the mess.
As suggested, instead of creating a public method, I left the method as private and changed the emailAddress(String name) and safeEmailAddress(String name) methods to use it. This way, it is transparent to users.
According to the diff, it seems that this time I didn't mess up the formatting, and I ran all the tests and none of them failed.
> Fixed toLocalPart; Fixed tests; Fixed formatting

- src/main/java/net/datafaker/providers/base/BaseProviders.java
- src/main/java/net/datafaker/providers/base/Credential.java
- src/main/java/net/datafaker/providers/base/Internet.java
- src/main/java/net/datafaker/service/files/EnFile.java
- src/main/resources/en/credential.yml
- src/test/java/net/datafaker/providers/base/CredentialTest.java
- src/test/java/net/datafaker/providers/base/InternetTest.java
Creates a new provider, `Credential`, whose purpose is to centralize the creation of credential-related data, such as user names, IDs, passwords, keys, etc.
In addition to the methods that already existed in the `Internet `provider (which were marked as deprecated), two new methods were created to assist in the creation of weak passwords (black list) and user IDs.
Improved test coverage for `Internet `provider.
> Creates new Credential provider; Deprecated Internet provider methods

- src/main/java/net/datafaker/idnumbers/BrazilIdNumber.java
- src/main/java/net/datafaker/idnumbers/pt/br/IdNumberGeneratorPtBrUtil.java
- src/main/java/net/datafaker/providers/base/IdNumber.java
- src/main/resources/META-INF/services/net.datafaker.idnumbers.IdNumberGenerator
- src/test/java/net/datafaker/helpers/IdNumberPatterns.java
- src/test/java/net/datafaker/idnumbers/pt/br/IdNumberGeneratorPtBrUtilTest.java
- src/test/java/net/datafaker/providers/base/CPFTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
Brazilian ID Number (aka CPF) was already available via 
```java
faker.cpf().valid()
```
but now it's also available via more generic 
```java
new Faker(new Locale("pt", "BR")).idNumber().valid()
```
> make Brazilian ID Number accessible via `faker.idNumber()`

- src/main/java/net/datafaker/providers/base/Finance.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
Adds support for generating IBAN numbers for Burundi, Djibouti, Falkland Islands, Honduras, Libya, Mongolia, Nicaragua, Oman, Russia, Sudan, Somalia and Yemen.
Updates IBAN format for Finland
Adds BBAN formats to source for easier comparison next time around
> Finance Provider - update Swift IBAN data standard from v87 to v99

- src/main/java/net/datafaker/providers/base/Internet.java
- src/main/java/net/datafaker/providers/base/Name.java
Since Internet#usernam() was already changed to use Credentials#username() all internal use may as well do the same thing so that DF itself isn't using deprecated methods.
> Stop using Internet#username() interally

- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/test/java/net/datafaker/transformations/JavaObjectTransformerConstructorTest.java
…using a method called `getParameterlessPublicConstructor`.
This fixes #1689 where the no-argument constructor is not always the one you get
> Retrieve the no-argument constructor
