datafaker-net/datafaker

- README.md
- src/main/java/net/datafaker/CNPJ.java
- src/main/java/net/datafaker/CPF.java
- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/idnumbers/pt/br/DocumentFormatterUtil.java
- src/main/java/net/datafaker/idnumbers/pt/br/IdNumberGeneratorPtBrUtil.java
- src/test/java/net/datafaker/CNPJTest.java
- src/test/java/net/datafaker/CPFTest.java
- CNPJ: legal entity identification document generator
- CPF: natural person identification document generator
> Add Brazil Document Generators

- README.md
Currently link https://www.datafaker.net/docs/ leads to 404 page
> Use existing link to documentation

- src/main/java/net/datafaker/Nation.java
- src/test/java/net/datafaker/NationTest.java
The PR adds generation of ISO language and countries based on java `Locale#getISOLanguages` and `Locale#getISOCountries`
> Add ISO language and country

- src/main/java/net/datafaker/service/FakeValuesService.java
The PR adds cache for methods which will speed up all the code going through `faker#expression`
I made some measurements
before
```
Benchmark                            Mode  Cnt    Score   Error   Units
JmhTest._bothifyExpression          thrpt    5  157.984 ± 2.141  ops/ms
JmhTest._letterifyExpression        thrpt    5  161.506 ± 1.238  ops/ms
JmhTest._optionsExpression          thrpt    5  126.751 ± 6.211  ops/ms
JmhTest._regexifyExpression         thrpt    5  120.731 ± 2.774  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  124.431 ± 0.641  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   31.784 ± 0.090  ops/ms
```
after
```
Benchmark                            Mode  Cnt    Score    Error   Units
JmhTest._bothifyExpression          thrpt    5  533.255 ± 22.638  ops/ms …
```
> Add cache for methods

- src/main/java/net/datafaker/service/FakeValues.java
The PR moves creation of input streams to try resource blocks to prevent possible leaks
> Make open streams in try catch

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/files/EnFile.java
The PR refactors `EnFile` to speed it up
benchmark before
```
Benchmark           Mode  Cnt     Score   Error   Units
JmhTest.initFaker  thrpt    5    44.192 ± 0.733  ops/ms
```
and after
```
Benchmark           Mode  Cnt    Score   Error   Units
JmhTest.initFaker  thrpt    5  138.761 ± 2.593  ops/ms
```
benchmark'c code
```java
@Benchmark
public void initFaker(Blackhole blackhole) {
blackhole.consume(new Faker());
}
```
> Refactor EnFile to speed it up

- src/main/java/net/datafaker/service/FakeValuesService.java
The idea of the PR is that usually users use the same or similar expressions in cycle. In this case their suppliers could be cached to save time on resolving.
It leads to some improvement like
before
```
JmhTest._bothifyExpression          thrpt    5  1829.098 ± 16.737  ops/ms
JmhTest._letterifyExpression        thrpt    5  1775.457 ±  9.980  ops/ms
JmhTest._optionsExpression          thrpt    5  1052.901 ± 16.139  ops/ms
JmhTest._regexifyExpression         thrpt    5   366.460 ±  3.624  ops/ms
JmhTest.firstName                   thrpt    5   994.682 ±  8.504  ops/ms
JmhTest.initFaker                   thrpt    5   250.549 ±  2.140  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5   873.172 ± 20.675  ops/ms …
```
> Cache resolved suppliers for expressions

- src/main/java/net/datafaker/fileformats/Csv.java
- src/main/java/net/datafaker/fileformats/Json.java
- src/test/java/net/datafaker/fileformats/CsvTest.java
- src/test/java/net/datafaker/fileformats/JsonTest.java
The PR adds generation of json based on map of suppliers.
e.g.
```java
public static void main(String[] args) {
// If order is not important other maps e.g. HashMap could be used
Map<Supplier<String>, Supplier<Object>> map = new LinkedHashMap<>();
Map<Supplier<String>, Supplier<Object>> nested = new LinkedHashMap<>();
nested.put(() -> "nestedkey", () -> "nestedvalue");
map.put(() -> "key", () -> "value");
map.put(() -> "nullValue", () -> null);
map.put(() -> "number", () -> 123);
map.put(() -> "boolean", () -> false);
map.put(() -> "array", () -> new Integer[] {123, 345, 31});
map.put(() -> "collection", () -> Arrays.asList("one", "two", "three"));
map.put(() -> "object", () -> nested);
Json json = new Json(map);
System.out.println(json.generate());
}
```
will give output
```json
{"key": …
```
> Add json generation

- src/main/java/net/datafaker/FakeCollection.java
- src/main/java/net/datafaker/fileformats/Yaml.java
- src/test/java/net/datafaker/fileformats/YamlTest.java
The PR adds support for yaml generation
e.g. 
```java
public static void main(String[] args) {
Map<Supplier<String>, Supplier<Object>> map = new LinkedHashMap<>();
Map<Supplier<String>, Supplier<Object>> address = new LinkedHashMap<>();
Map<Supplier<String>, Supplier<Object>> phones = new LinkedHashMap<>();
phones.put(() -> "worknumbers", () -> new FakeCollection.Builder<String>().suppliers(() -> faker.phoneNumber().phoneNumber()).maxLen(2).build().get());
phones.put(() -> "cellphones", () -> new FakeCollection.Builder<String>().suppliers(() -> faker.phoneNumber().cellPhone()).maxLen(3).build().get());
address.put(() -> "city", () -> faker.address().city());
address.put(() -> "country", () -> faker.address().country());
address.put(() -> "streetAddress", () -> …
```
> Add yaml generation

- src/main/java/net/datafaker/IdNumber.java
- src/main/java/net/datafaker/idnumbers/PeselNumber.java
- src/test/java/net/datafaker/IdNumberTest.java
- src/test/java/net/datafaker/idnumbers/PeselNumberTest.java
This is a generator of a [Polish PESEL number](https://en.wikipedia.org/wiki/PESEL).
> feat: add PESEL number generator

- src/main/java/net/datafaker/fileformats/Xml.java
- src/test/java/net/datafaker/fileformats/XmlTest.java
The PR adds support for xml generation
It is possible to specify attributes and children and values
e.g. 
```java
public static void main(String[] args) {
Collection<Xml.XmlNode> address = new FakeCollection.Builder<Xml.XmlNode>()
.suppliers(() -> new Xml.XmlNode("address",
map(entry("country", faker.address().country()),
entry("city", faker.address().city()), entry("streetAddress", faker.address().streetAddress())), Collections.emptyList()))
.maxLen(3).build().get();
Collection<Xml.XmlNode> persons = new FakeCollection.Builder<Xml.XmlNode>()
.suppliers(() -> new Xml.XmlNode("person",
map(entry("firstname", faker.name().firstName()),
entry("lastname", faker.name().lastName())),
of(new Xml.XmlNode("addresses", address)))).maxLen(3).build().get();
String str = new …
```
> Add xml generation

- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/CustomFakerTest.java
- src/test/rockets.yml
- src/test/rockets2.yml
The PR adds possibility to add files with custom data for custom fakers
An example is at `src/test/java/net/datafaker/CustomFakerTest.java`
> Custom fakers and files with custom data

- src/main/java/net/datafaker/service/FakeValuesService.java
Currently cache contains suppliers which then should resolve methods and then do invoke. In fact it is possible to keep result of resolving in cache. The PR does this
as a result it speeds up some benchmarks 
before
```
JmhTest._optionsExpression          thrpt    5  1610.219 ± 24.256  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  1273.391 ± 33.416  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   407.451 ± 35.170  ops/ms
``` 
after
```
JmhTest._optionsExpression          thrpt    5  4713.630 ± 48.540  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  2277.320 ± 30.705  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5 …
```
> Cache supplier for invocation rather than method resolving

- src/main/java/net/datafaker/service/FakeValuesService.java
The second part with caching for methods, missed in the 1-st part
before
```
JmhTest._bothifyExpression          thrpt    5  2730.742 ± 27.647  ops/ms
JmhTest._csv                        thrpt    5    29.307 ±  0.157  ops/ms
JmhTest._letterifyExpression        thrpt    5  2540.297 ± 31.841  ops/ms
JmhTest._optionsExpression          thrpt    5  4608.701 ± 81.775  ops/ms
JmhTest._regexifyExpression         thrpt    5  1645.380 ± 18.166  ops/ms
JmhTest.oneMethodCallExpression     thrpt    5  2212.006 ± 32.020  ops/ms
JmhTest.threeMethodsCallExpression  thrpt    5   523.795 ± 10.756  ops/ms
```
after
```
JmhTest._bothifyExpression          thrpt …
```
> Cache supplier for invocation rather than method resolving part 2

- docs/documentation/date-format.md
- mkdocs.yml
The PR adds description of date-format feature introduced at https://github.com/datafaker-net/datafaker/pull/15
> Add date format description

- src/main/java/net/datafaker/DateAndTime.java
- src/test/java/net/datafaker/DateAndTimeTest.java
The PR addresses feedback for https://github.com/datafaker-net/datafaker/pull/72
> ChronoUnit could be used as an argument while Duration generation

- docs/documentation/expressions.md
- mkdocs.yml
The PR add description of expression usage to the doc
> Add description of expressions to doc

- src/main/java/net/datafaker/service/RandomService.java
The PR propagates ThreadLocal streams: ints, longs, doubles
> Propagate thread local streams

- src/main/java/net/datafaker/FakeCollection.java
- src/test/java/net/datafaker/FakeCollectionTest.java
The PR adds toCsv method for fake collections to transform collections to csv
> Add toCsv for fake collections

- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
right now only English is preloaded into memory and prevent re-read the files, 
this change would make to lazy cache all locales so we have the performance gains when using multiple languages.
> Lazy cache all locale values

- .github/workflows/deploy.yml
- .github/workflows/maven.yml
- .gitignore
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Add mvn wrapper to ensure existence of maven of the required version
> Add maven wrapper

- src/main/java/net/datafaker/fileformats/Json.java
- src/test/java/net/datafaker/fileformats/JsonTest.java
The PR adds support of nested json, e.g.
```java
public static void main(String[] args) {
Map<Supplier<String>, Supplier<Object>> map4Nested = new HashMap<>();
map4Nested.put(() -> "key", () -> "value");
Json nestedJson = new Json(map4Nested);
Map<Supplier<String>, Supplier<Object>> map = new HashMap<>();
map.put(() -> "key", () -> nestedJson);
Json json = new Json(map);
System.out.println(json.generate());
}
```
will output
```
{"key": {"key": "value"}}
```
> Nested json support

- docs/documentation/file-formats.md
The PR updates doc for json based on last json related changes
> Update documentation for json

- docs/documentation/file-formats.md
Update documentation with json escaped
> Add example with json escaped payload

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
- src/test/test.txt
The PR adds support of expressions for files
> Add expression for files

- docs/documentation/file-formats.md
Currently example of csv generation in docs is outdated and not compiled. 
This PR is going to fix it
> Fix example of csv generation in docs

- README.md
- src/test/java/net/datafaker/fileformats/CsvTest.java
To enhance the first look at github the PR is intending to add some features description at README page
> Add description of some features at README

- README.md
- src/main/java/net/datafaker/EldenRing.java
- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/service/files/EnFile.java
- src/main/resources/en/elden_ring.yml
- src/test/java/net/datafaker/EldenRingTest.java
- src/test/java/net/datafaker/integration/FakerIT.java
Please check it and notice us if there is any problem. Thanks a lot.
---- SE_SUSTech, group: Lanrand
> Solve https://github.com/DiUS/java-faker/issues/707.

- src/test/java/net/datafaker/OscarMovieTest.java
The PR fixes failing test https://github.com/datafaker-net/datafaker/runs/6147230358?check_suite_focus=true
> Actor name from OscarMovie could contain single quote

- src/main/resources/en-PH.yml
Add basic philippines locale. Internet and email
> add ph-locale: internet, email

- src/test/java/net/datafaker/service/FakeValuesTest.java
The PR adds tests for equal/not equal fake values
> Add tests for equal/not equal FakeValues

- README.md
- docs/documentation/expressions.md
- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/fileformats/Csv.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
Support generation of csv via expressions
> Add csv generation via expression

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
The PR makes possible to escape quotes in expressions in SQL way (`''`)
e.g.
```
#{options.option ''''}
```
will generate `'`
> Add possibility to escape quotes in expressions

- README.md
- docs/documentation/expressions.md
- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/fileformats/Json.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
Support generation of json via expressions
> Add json generation via expression

- src/main/java/net/datafaker/Faker.java
- src/main/java/net/datafaker/Time.java
- src/test/java/net/datafaker/TimeTest.java
The PR allows time generation and usage of time in expressions
> Add support of time generation

- src/main/java/net/datafaker/DateAndTime.java
- src/test/java/net/datafaker/DateAndTimeTest.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
Use `Timestamp` in `DateAndTime` as child of `Date` and having a more friendly `toString`
> Use timestamp as a child for Date having more friendly toString

- src/main/resources/en-PH.yml
Add most popular philippines names
> add philippines first_name and last_name

- src/main/java/net/datafaker/service/FakeValuesService.java
The PR adds caching of parsed args and keys.
That speeds up cases for expression (up to 50%) based generation like
before
```
Benchmark                            Mode  Cnt     Score     Error   Units
JmhTest._bothifyExpression           thrpt    5  1047.055 ±   5.959  ops/ms
JmhTest._letterifyExpression         thrpt    5   948.810 ± 146.551  ops/ms
JmhTest._oneMethodCallExpression     thrpt    5   666.582 ±   5.509  ops/ms
JmhTest._optionsExpression           thrpt    5   584.529 ±  12.425  ops/ms
JmhTest._regexifyExpression          thrpt    5   911.788 ±  15.694  ops/ms
JmhTest._threeMethodsCallExpression  thrpt    5   234.992 ±  11.027  ops/ms
JmhTest.csvCall                      thrpt    5    75.119 ±   2.116  ops/ms
JmhTest.jsonCall                     thrpt    5    49.711 ± …
```
> Add caching of parsed args and keys

- src/main/java/net/datafaker/service/FakeValuesService.java
The PR does 2 things
1, caches constructors that allows to speed up cases for expressions where methods with varargs are used
2. eliminates issues with cases where there are several methods with same name however with a little bit different signature e.g.
`Option.option(Object[] options)` and `Options.option(String[] options)`
> Add cache for constructors

- src/test/java/net/datafaker/FamousLastWordsTest.java
Since there is an option with dots, this symbol should be added to regex
> Add dots as possible symbols for famous last words

- src/main/java/net/datafaker/service/FakeValuesService.java
There is a useless arg in `resolveExpression` method
> Remove useless args

- README.md
The PR adds providers for README which are already implemented however were not added to README for some reason
> Update README with existing providers

- src/main/java/net/datafaker/Name.java
The PR optimizes username by removal of regexp
Before
```
Benchmark                                     Mode  Cnt    Score   Error   Units
DatafakerBenchmark.dataFaker_username        thrpt    5  257.866 ± 3.375  ops/ms
```
After
```
Benchmark                                     Mode  Cnt    Score   Error   Units
DatafakerBenchmark.dataFaker_username        thrpt    5  304.477 ± 4.892  ops/ms
```
> Optimize username

- src/test/java/net/datafaker/AddressTest.java
- src/test/java/net/datafaker/AppTest.java
- src/test/java/net/datafaker/DurationTest.java
- src/test/java/net/datafaker/FakeCollectionTest.java
- src/test/java/net/datafaker/FakerTest.java
- src/test/java/net/datafaker/HearthstoneTest.java
- src/test/java/net/datafaker/InternetTest.java
- src/test/java/net/datafaker/LoremTest.java
- src/test/java/net/datafaker/NationTest.java
- src/test/java/net/datafaker/fileformats/XmlTest.java
- src/test/java/net/datafaker/fileformats/YamlTest.java
- src/test/java/net/datafaker/idnumbers/PeselNumberTest.java
- src/test/java/net/datafaker/service/FakeValuesGroupingTest.java
- src/test/java/net/datafaker/service/FakeValuesServiceTest.java
- src/test/java/net/datafaker/service/RandomServiceTest.java
There are complex assertJ statements which could be simplified. This PR does this work
> Simplify some assertJ statements

- src/main/java/net/datafaker/Medical.java
The PR fixes failing test at https://github.com/datafaker-net/datafaker/runs/6641995024?check_suite_focus=true
> Fix medical.testBloodGroup

- src/main/java/net/datafaker/service/FakeValuesService.java
Add caching speeds up a bit some cases
Before
```
Benchmark                                  Mode  Cnt      Score     Error   Units
DatafakerExpressions.bothifyExpression    thrpt   10   2169.941 ± 45.504  ops/ms
DatafakerExpressions.letterifyExpression  thrpt   10   2104.585 ± 81.704  ops/ms
DatafakerExpressions.regexifyExpression   thrpt   10   1607.923 ± 34.328  ops/ms
```
After
```
Benchmark                                  Mode  Cnt      Score     Error   Units
DatafakerExpressions.bothifyExpression    thrpt   10   2283.968 ±  33.019  ops/ms
DatafakerExpressions.letterifyExpression  thrpt   10   2367.088 ±  61.098  ops/ms
DatafakerExpressions.regexifyExpression   thrpt   10   2140.930 ±  61.182  ops/ms
```
> Add caching for methods with coerced args

- src/main/java/net/datafaker/service/FakeValuesService.java
Currently datafaker tries to resolve the result of expression as well and this is useless.
The PR is aiming to stop it
> Stop resolving expressions if there is no any more expressions

- src/main/java/net/datafaker/Address.java
- src/test/java/net/datafaker/AddressTest.java
Generates formatted lat/lon and lon/lat coordinates. Apparently there's not really a standard: https://observablehq.com/@clhenrick/lat-lon-or-lon-lat
Need this for a project I'm working on.
> im(address): Added latLon and latLon coordinates

- src/main/java/net/datafaker/idnumbers/NricNumber.java
Use `EnumMap` for `NricNumber`
> Use Enum map for Nric number

- src/main/java/net/datafaker/idnumbers/ZhCnIdNumber.java
> Fix zh_CN ID number generator to match correct format

- src/main/resources/en-MS.yml
Issue: #163 
Error count: +- 20
> Fix phone number formats for en-MS

- src/main/resources/en-NZ.yml
Issue: #163 
Error count: +- 23
> Fix phone number formats for en-NZ

- src/main/resources/pt.yml
> Fix phone number formats for pt-PT

- src/main/resources/pt-BR.yml
Issue: #163 
Improved error count from +-50 to 0
> Fix phone number formats for pt-BR

- src/main/resources/fi-FI.yml
> Fix phone number formats for fi_FI

- README.md
PR adds example of Jshell's usage
> Add JShell example

- src/main/resources/de.yml
Base Pattern:
char{1-3} char{2} number {1-4}
Extension for E(electric) and H(historic)
> Add german license plates

- src/main/resources/en-IND.yml
> Fix phone number formats for en_IND locale

- src/main/resources/th.yml
> Fix phone number formats for 'th_TH' locale

- src/main/resources/ja.yml
- src/test/java/net/datafaker/PassportTest.java
> Support japan passport number

- .github/workflows/release.yml
* Added release action.
* Added release action.
* Added release action.
> Release (#333)

- docs/releases/1.6.0.md
> Fix 1.6.0 release date

- .github/workflows/deploy.yml
- .github/workflows/maven.yml
- .github/workflows/release.yml
Apply ci changes for renaming of master to main
> Apply renaming master to main

- src/main/java/net/datafaker/Barcode.java
The PR simplify ean generation + optimizes it by removal of useless toString and toLong transformations
> Refactor barcode

- docs/documentation/file-formats.md
> Add new JSON generation example in file formats docs

- src/main/resources/es.yml
- src/test/java/net/datafaker/PassportTest.java
Issue: #268 
Added Spain passport number format, and added tests for uncoveraged passport number formats
> Add 'es' passport number, add tests for uncoveraged passport numbers

- src/test/java/net/datafaker/script/ProvidersDocsGenerator.java
Support the `group` column in `providers.md`
> Add support of groups to 'ProvidersDocsGenerator'

- .github/workflows/deploy.yml
- .github/workflows/maven.yml
Through -Dstyle.color=always just after --batch-mode
> Colorize Maven output in GitHub Actions

- src/test/java/net/datafaker/providers/base/CNPJTest.java
> CNPJ test was flaky, fixed now.

- src/main/java/net/datafaker/providers/base/Text.java
> Remove useless comments

- README.md
- src/main/java/net/datafaker/providers/videogame/MarvelSnap.java
- src/main/java/net/datafaker/providers/videogame/VideoGameProviders.java
- src/main/java/net/datafaker/service/files/EnFile.java
- src/main/resources/en/marvel_snap.yml
- src/test/java/net/datafaker/providers/videogame/MarvelSnapTest.java
Added provider for the new trading card game called Marvel Snap
> Add Marvel Snap Provider

- src/main/java/net/datafaker/providers/base/Company.java
- src/main/java/net/datafaker/providers/base/DateAndTime.java
Precollect buzzwords instead of reading it each time.
> Precollect buzzwords

- src/main/java/net/datafaker/providers/base/DateAndTime.java
- src/main/java/net/datafaker/providers/base/Time.java
- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
The PR is to extract some vars to avoid code duplication
> Refactor: extract some vars

- docs/documentation/performance170.md
- mkdocs.yml
There is a new measumernts against datafaker 1.7.0 and others recent libs
> Add perf tests for 1.7.0

- src/main/java/net/datafaker/service/FakerContext.java
It allows to speed up initialization a bit
before
```
Benchmark                                          Mode  Cnt     Score    Error   Units
DatafakerInitialization.dataFaker_initialization  thrpt   10  2524.923 ± 74.487  ops/ms
```
after
```
DatafakerInitialization.dataFaker_initialization  thrpt   10  2982.410 ± 36.679  ops/ms
```
> Cache calculated locale chains

- src/test/java/net/datafaker/providers/entertainment/AvatarTest.java
- src/test/java/net/datafaker/providers/entertainment/OscarMovieTest.java
Minor changes to address build complaints in Eclipse
> Entertainment Fixes

- pom.xml
Reverts datafaker-net/datafaker#667
> Revert "implement currently passing Xlint checks"

- src/main/resources/en/device.yml
- Reformat device.yml
- Add new devices and manufactures to device.yml
> Reformat and Enrich device.yml

- FIRST_TIME_CONTRIBUTOR.md
- README.md
- docs/documentation/first-time-contributor.md
- mkdocs.yml
- Add a first time contributor guide and add it to the README.MD and the mkdocs
I myself am a first time contributor (both to the project and open source). I have made some assumptions so that _something_ can be written but please do correct me on any assumptions that may be false. This is all quite meta 😄
> Add first time contributor guide

- pom.xml
> build(deps): bump snakeyaml from 1.33 to 2.0

- docs/documentation/schemas.md
> Fix Kotlin examples in Transformers documentation

- src/main/resources/en/australia.yml
- Update typo in Victoria
- Add a few more iconic Australian locations and animals
> Update Australia resource typo and add places and animals

- src/main/java/net/datafaker/internal/helper/WordUtils.java
The PR is addressing feedback at https://github.com/datafaker-net/datafaker/pull/749#discussion_r1154809723
//cc @kingthorin
> Return input value instead of intantiating a new one

- docs/documentation/expressions.md
fix invalid string in csv expression example
> fix csv expression example in expressions.md

- pom.xml
I hope this will fix exceptions in Java 20 Github Actions
> Update jacoco-maven-plugin from 0.8.8 to 0.8.9

- src/test/java/net/datafaker/providers/base/DiseaseTest.java
Since now tests able to read data from file to construct expected set we don't need to call tests thousand number of times
> Remove unused package private method and tests

- pom.xml
> Update mockito from 5.2.0 to 5.3.0

- LICENSE
- README.md
- docs/documentation/license.md
- pom.xml
Example of MANIFEST.MF:
```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 17
Specification-Title: Datafaker
Specification-Version: 2.0
Implementation-Title: Datafaker
Implementation-Version: 2.0.0-SNAPSHOT
```
Ref #794
> Configured Maven to create a MANIFEST file. Renamed Data Faker to Datafaker

- src/main/java/net/datafaker/annotations/FakeResolver.java
- src/main/java/net/datafaker/providers/base/AbstractProvider.java
- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/RegExpContext.java
- src/main/java/net/datafaker/transformations/CompositeField.java
- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/main/java/net/datafaker/transformations/Schema.java
- src/main/java/net/datafaker/transformations/SimpleField.java
This improvement brings about 25% of speed
before
```
Benchmark                                                 Mode  Cnt    Score   Error  Units
Datafaker_JavaObjectPopulateBenchmark.javaObjectPopulate  avgt   10  315.623 ± 2.223  ms/op
```
after
```
Benchmark                                                 Mode  Cnt    Score    Error  Units
Datafaker_JavaObjectPopulateBenchmark.javaObjectPopulate  avgt   10  242.836 ± 10.768  ms/op
```
> Cache suppliers for java transformers, improve hashing

- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesContext.java
- src/main/java/net/datafaker/service/FakeValuesGrouping.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/service/FakeValuesGroupingTest.java
- src/test/java/net/datafaker/service/FakeValuesTest.java
Backport of #767 to 1.x as part of #770 backport 
almost git cherry-pick
> [Backport - 1.x] Introduce FakeValuesContext and FAKE_VALUES_MAP (#767)

- src/main/java/net/datafaker/service/FakeValues.java
- src/main/java/net/datafaker/service/FakeValuesContext.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/FakerContext.java
- src/main/java/net/datafaker/service/RegExpContext.java
Backport of #792 to 1.x as part of #770 backport
almost cherry-pick
> [Baackport-1.x]   Introduce cache of suppliers and remove usage of Objects.hash to speed up

- src/main/java/net/datafaker/annotations/FakeResolver.java
This is a backport of #809 
git cherry-pick
> [Backport-1.x] Add cache for default schemas to FakeResolver

- src/main/java/net/datafaker/annotations/FakeResolver.java
- src/main/java/net/datafaker/providers/base/AbstractProvider.java
- src/main/java/net/datafaker/providers/base/BaseFaker.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/main/java/net/datafaker/service/RegExpContext.java
- src/main/java/net/datafaker/transformations/CompositeField.java
- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/main/java/net/datafaker/transformations/Schema.java
- src/main/java/net/datafaker/transformations/SimpleField.java
Backport of #810 to 1.x as part of #770 backport
> [Backport-1.x] Cache suppliers for java transformers, improve hashing (#810)

- src/main/java/net/datafaker/annotations/FakeResolver.java
- src/main/java/net/datafaker/internal/helper/COWMap.java
- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/Issue759.java
> [Backport-1.x] Make FakeValuesService thread safe (#770)

- src/main/java/net/datafaker/providers/base/Finance.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
> [Backport-1.x]  Generating US routing number (ABA RTN) in Finance provider (#821).

- src/main/java/net/datafaker/providers/base/Azure.java
- src/test/java/net/datafaker/providers/base/AzureTest.java
Add support for Azure Spring Apps (https://azure.microsoft.com/en-au/products/spring-apps/)
> chore: add support for Azure Spring Apps

- docs/releases/2.0.0.md
Per discussion in datafaker-net/datafaker#856
> Update 2.0.0 docs with breaking change

- src/main/java/net/datafaker/service/RandomService.java
- src/test/java/net/datafaker/FakerTest.java
The absence of hashcode/equals was the reason of map growing at #883
> Add hashcode and equals to RandomService

- src/test/java/net/datafaker/providers/base/BookTest.java
- src/test/java/net/datafaker/providers/base/CompanyTest.java
just because it starts failing time to time
for instance https://github.com/datafaker-net/datafaker/actions/runs/5553647738/jobs/10142451230#step:4:1017
> There could be a dot in company name

- src/test/java/net/datafaker/providers/base/NameTest.java
e.g. https://github.com/datafaker-net/datafaker/actions/runs/5554020338/jobs/10143304541#step:5:1027
> NameTest testname could be flaky

- src/test/java/net/datafaker/FakerTest.java
- src/test/java/net/datafaker/integration/FakerRepeatabilityIntegrationTest.java
- src/test/java/net/datafaker/providers/base/BaseFakerTest.java
- src/test/java/net/datafaker/providers/base/NameTest.java
This should allow to avoid impact of other tests on it and should fix 
such flaky issue https://github.com/datafaker-net/datafaker/actions/runs/5596562572/jobs/10234110845#step:4:1039
> Extract FakerRepeatabilityIntegrationTest to integration test phase

- pom.xml
Completely isolate this test into a separate `integration test` phase
> Isolate FakerRepeatabilityIntegrationTest into a separate integration test phase

- .github/workflows/maven.yml
suddenly `mvn package` does not run integration test phase =)
> Use verify in ci

- .github/workflows/maven.yml
Just an attempt to fix Codecov
> Simplified Codecov

- src/main/resources/en/chuck_norris.yml
- src/main/resources/en/star_wars.yml
First time contributing :
- Added a funny Chuck Norris quote
- Added the Star Wars planet of Christophsis
- Added Obi-wan famous quote from Episode III
Tell me your feedback, I'd be pleased to edit my changes :)
> Feat: add chuck norris quote, star-wars planet and obi-wan quote

- pom.xml
- src/main/java/net/datafaker/transformations/JavaObjectTransformer.java
- src/test/kotlin/net/datafaker/example/SchemaExampleTest.kt
Should fix https://github.com/datafaker-net/datafaker/issues/918
> Added support for Kotlin Data classes.

- src/main/java/net/datafaker/providers/base/Finance.java
Instead of usage of regexp and replaces use more optimal way
> Speed up creadit card

- src/main/java/net/datafaker/providers/base/Finance.java
Remove useless array and its creation
> Speed up iban

- src/main/java/net/datafaker/providers/base/Company.java
Remove regexp to speed up `domainName`
> Speed up net.datafaker.providers.base.Company#domainName

- src/main/java/net/datafaker/providers/base/Number.java
- src/test/java/net/datafaker/formats/CsvTest.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/formats/SqlTest.java
- src/test/java/net/datafaker/providers/base/NumberTest.java
In fact for amlitude we only need to check whether it is not negative or not
> Speed up number between

- src/test/java/net/datafaker/providers/base/TireTest.java
It seems prefix could contain 3 digits as well
like here https://github.com/datafaker-net/datafaker/actions/runs/5948774981/job/16133232260?pr=934#step:4:971
> Make TireTest more stable

- src/main/java/net/datafaker/providers/base/Twitter.java
Several optimizations like extraction of logger to `static final`, use of `DateTimeFormatter` instead of `SimpleDateFormat`, usage of `StringBuilder`
> Optimize Twitter#twitterId

- docs/documentation/usage.md
Update usage.md with an Option.option example.
Fixes datafaker-net/datafaker#888
> docs: Random generator from java Enums

- src/main/java/net/datafaker/idnumbers/SvSEIdNumber.java
It speeds validation up since no need for creation of strings during substriging
> Use char to int cast in SvSEIdNumber when possible

- src/main/java/net/datafaker/idnumbers/EsMXIdNumber.java
The logic for leap year is incorrect since not every fourth year is a leap year
> Correct logic for leap year

- src/main/java/net/datafaker/idnumbers/KoKrIdNumber.java
Replace `SimpleDateFormat` allows to give speed about 2x times speed
> Speed up getValidRrn

- src/main/java/net/datafaker/idnumbers/EsMXIdNumber.java
- src/main/java/net/datafaker/providers/base/Options.java
- src/test/java/net/datafaker/idnumbers/EsMXIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/KoKrIdNumberTest.java
There is a number of vars like lists, regexps, datetimeformatter which could be extracted on constant level and as a result improve speed
> Speed validEsMXSsn by extraction vars

- src/main/java/net/datafaker/providers/base/Lorem.java
The idea is to capitalize just one word to minimize substring.
Also no need to create list of strings, just concatenate them as soon as possible
> Speed up Lorem#sentence

- src/main/java/net/datafaker/providers/base/Internet.java
- src/test/java/net/datafaker/providers/base/InternetTest.java
Also includes speed improvements as a side effect
> Use array of chars for getIpV6Address instead of StringBuilder

- src/main/java/net/datafaker/idnumbers/SvSEIdNumber.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
Also adds test to check whether it contains a valid date or not
should fix #986
> SvSe id number should contain valid date

- src/main/java/net/datafaker/idnumbers/SvSEIdNumber.java
- src/main/java/net/datafaker/providers/base/DateAndTime.java
- src/test/java/net/datafaker/idnumbers/SwedishIdNumberTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
There is no need for repeatedly generation of new id until the lucky one...
Instead just generate the correct one with the first attempt
also allows to speed up generation as a result
kind of follow up for #987
> Use generation of birthday instead of loop

- src/main/java/net/datafaker/idnumbers/EnZAIdNumber.java
- src/test/java/net/datafaker/idnumbers/EnZAIdNumberTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
The PR is similar to https://github.com/datafaker-net/datafaker/pull/989 however for another Id generation
> Use generation of birthday instead of loop for EnZA

- .github/workflows/maven.yml
> Use temurin

- README.md
just make in sync with what we have in `pom.xml`
> Use correct snapshot version in README

- src/main/java/net/datafaker/providers/base/Name.java
- src/test/java/net/datafaker/providers/base/NameTest.java
Fixes https://github.com/datafaker-net/datafaker/issues/999
> Added support for male and female names.

- README.md
- src/main/java/net/datafaker/providers/base/BaseProviders.java
- src/main/java/net/datafaker/providers/base/LanguageCode.java
- src/test/java/net/datafaker/providers/base/LanguageCodeTest.java
PR with suggestion for issue https://github.com/datafaker-net/datafaker/issues/1017
Closes datafaker-net/datafaker#1017
> Add language code provider

- src/main/resources/tr.yml
I added more data for the tr.yml file.
> Update for tr.yml

- pom.xml
- src/main/java/module-info.java
Support for modular projects, fixes #1020
> added module-info.java

- README.md
So that users don’t try to visit it and get lost in the vast number of folders etc
> Update README - Code fence snapshot location

- src/main/java/net/datafaker/providers/base/Locality.java
> Parent file could be null if resource is in jar

- pom.xml
could be checked by looking into produced jar
> Shading for rgxgen doesn't work

- LICENSE
- README.md
- docs/documentation/license.md
- mkdocs.yml
A bit late however anyway need to update year
> Happy new 2024

- LICENSE
It seems the current Apache license isn't detected well, so let's try with this.
> Proper Apache 2.0 LICENSE

- pom.xml
> Use correct group name for rgxgen shading

- src/main/resources/pt-BR.yml
Only nationalities translated into pt-BR.
> Nationalities translated into pt-BR

- src/moditect/module-info.java
it was removed at https://github.com/datafaker-net/datafaker/pull/1244
> Remove formats package since it was removed from src as well

- src/main/java/net/datafaker/idnumbers/AlbanianIdNumber.java
- src/main/java/net/datafaker/idnumbers/BulgarianIdNumber.java
- src/main/java/net/datafaker/idnumbers/MacedonianIdNumber.java
- src/main/java/net/datafaker/idnumbers/MoldovanIdNumber.java
- src/main/java/net/datafaker/idnumbers/RomanianIdNumber.java
- src/main/java/net/datafaker/idnumbers/Utils.java
- src/main/resources/META-INF/services/net.datafaker.idnumbers.IdNumberGenerator
- src/test/java/net/datafaker/idnumbers/AlbanianIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/RomanianIdNumberTest.java
- src/test/java/net/datafaker/idnumbers/UtilsTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
This PR allow generating ID numbers for Romania:
```java
Faker faker = new Faker(new Locale("ro", "RO"));
String idNumber = ROMANIAN.idNumber().valid();
assertThatPin(idNumber).matches("\\d{13}");
}
```
The implementation is in class RomanianIdNumber.java.
Other files are slightly changed just to reuse some existing code snippers (for calculating checksum etc.).
> Add support for Romanian ID numbers

- src/main/resources/en/kpop.yml
H.O.T., Fin.K.L - were missed in the generations list
Sunmi, Stray Kids - were missed in all the lists
> Fix for K-pop artist lists: H.O.T., Fin.K.L, Sunmi, Stray Kids

- README.md
- docs/releases/2.4.1.md
- docs/releases/2.4.2-SNAPSHOT.md
- mkdocs.yml
> Release notes for version 2.4.1.

- pom.xml
> Update snapshot version in pom.xml

- .github/workflows/pom_update.yml
Specifically/only add pom.xml to the commit.
> Minor fix to POM update workflow

- src/main/java/net/datafaker/idnumbers/FrenchIdNumber.java
- src/main/resources/META-INF/services/net.datafaker.idnumbers.IdNumberGenerator
- src/test/java/net/datafaker/helpers/IdNumberPatterns.java
- src/test/java/net/datafaker/idnumbers/FrenchIdNumberTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
* Add a French id number generator and unit tests.
* Extract id number patterns
> Add French id number generator

- src/test/java/net/datafaker/providers/base/PhoneNumberTest.java
942 is a new area code to be introduced in 2025, see https://www.newswire.ca/news-releases/new-area-code-942-to-be-introduced-in-ontario-in-2025-817201718.html
> add new Canadian area code 942

- src/main/java/net/datafaker/service/FakeValuesService.java
- src/test/java/net/datafaker/FakerTest.java
> Respect arg types while looking for method for expressions

- docs/documentation/providers.md
- src/main/java/net/datafaker/providers/videogame/Dota2.java
Commit for reference: https://github.com/datafaker-net/datafaker/commit/26e75e390d1d35dcad82822e1aa61b19c0122a93
> Fix 'since' version for Dota2 provider

- src/main/resources/en/stock.yml
Extension for Stock::exchanges
> Stock exchanges: MOEX, SGX, TSE, EURONEXT-DUBLIN, NZX

- docs/in-the-media/links.md
Refer to discussion in https://github.com/datafaker-net/datafaker/issues/1503
> Add Trino Community Broadcast 71: Fake it real good to Articles and News page

- src/main/java/net/datafaker/providers/base/Name.java
- src/test/java/net/datafaker/providers/base/NameTest.java
> Adjust malefirstName to align with its female counterpart, and java naming conventions - maleFirstName

- .github/workflows/release-from-tag.yml
- RELEASE_PROCESS.md
Should address https://github.com/datafaker-net/datafaker/issues/1488
> Use GitHub releases to create a release.

- src/main/java/net/datafaker/transformations/JsonTransformer.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/transformations/JsonTransformerTest.java
Fixes datafaker-net/datafaker#1556
> jsontransformer: All numbers as numbers

- src/main/java/net/datafaker/providers/base/Finance.java
I needed better docs from this page recently, and hated digging in the source for the answer. Fixed!
> Add missing javadoc for the Finance provider

- pom.xml
- src/main/java/net/datafaker/providers/base/BaseProviders.java
- src/main/java/net/datafaker/providers/base/IdNumber.java
- src/main/java/net/datafaker/providers/base/Lorem.java
- src/main/java/net/datafaker/providers/base/Name.java
- src/main/java/net/datafaker/providers/base/TimeAndDate.java
- src/test/java/net/datafaker/TestSetupExtension.java
- src/test/java/net/datafaker/formats/CsvTest.java
- src/test/java/net/datafaker/formats/JsonTest.java
- src/test/java/net/datafaker/formats/SqlTest.java
- src/test/java/net/datafaker/idnumbers/MexicanIdNumberTest.java
- src/test/java/net/datafaker/providers/base/CurrencyTest.java
- src/test/java/net/datafaker/providers/base/CustomFakerTest.java
- src/test/java/net/datafaker/providers/base/FinanceTest.java
- src/test/java/net/datafaker/providers/base/IdNumberTest.java
- src/test/java/net/datafaker/providers/base/InternetPasswordTest.java
- src/test/java/net/datafaker/providers/base/InternetTest.java
- src/test/java/net/datafaker/providers/base/MedicalTest.java
- src/test/java/net/datafaker/providers/base/TwitterTest.java
1. remove unneeded debug logs like "Starting test..."
2. fix multiple deprecation warnings
3. remove annoying SLF4J warning
> Less logs in tests

- src/main/java/net/datafaker/providers/base/Internet.java
Fixes https://github.com/datafaker-net/datafaker/issues/1658
> Added missing link for deprecation warning.

- src/main/resources/_PL.yml
> Update _PL.yml with country phone code
